#!/usr/bin/env tsx
/**
 * Downloads the voucher card fonts from Google Fonts and writes
 * src/lib/vouchers/card-fonts.ts with the WOFF2 files embedded as
 * base64 data-URI @font-face rules, so card rendering never depends
 * on a CDN (spec section 6, F24).
 *
 * Faces (all SIL OFL, redistribution permitted), latin subset only:
 * - DM Serif Display 400 (the card artwork uses no italic)
 * - Outfit 400 and 600
 * - Clicker Script 400
 *
 * Run: npx tsx scripts/vouchers/fetch-fonts.ts
 * On any download failure nothing is written and the script exits 1;
 * see the fallback notes in src/lib/voucher-card-template.ts.
 */
import { get } from 'node:https'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(SCRIPT_DIR, '../../src/lib/vouchers/card-fonts.ts')

// A browser UA is required: Google Fonts only serves woff2 URLs to
// clients that advertise woff2 support.
const CHROME_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

const FAMILY_CSS_URLS = [
  'https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap',
  'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&display=swap',
  'https://fonts.googleapis.com/css2?family=Clicker+Script&display=swap',
]

interface FontFace {
  family: string
  style: string
  weight: string
  url: string
  unicodeRange: string
}

function fetchBuffer(url: string, redirectsLeft = 3): Promise<Buffer> {
  return new Promise((resolvePromise, rejectPromise) => {
    const request = get(url, { headers: { 'User-Agent': CHROME_UA } }, response => {
      const status = response.statusCode ?? 0
      if (status >= 300 && status < 400 && response.headers.location && redirectsLeft > 0) {
        response.resume()
        resolvePromise(fetchBuffer(new URL(response.headers.location, url).toString(), redirectsLeft - 1))
        return
      }
      if (status !== 200) {
        response.resume()
        rejectPromise(new Error(`HTTP ${status} for ${url}`))
        return
      }
      const chunks: Buffer[] = []
      response.on('data', chunk => chunks.push(chunk as Buffer))
      response.on('end', () => resolvePromise(Buffer.concat(chunks)))
      response.on('error', rejectPromise)
    })
    request.on('error', rejectPromise)
  })
}

function parseLatinFaces(css: string): FontFace[] {
  const faces: FontFace[] = []
  const facePattern = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g
  let match: RegExpExecArray | null
  while ((match = facePattern.exec(css)) !== null) {
    const subset = match[1]
    if (subset !== 'latin') continue
    const block = match[2]
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
    const style = /font-style:\s*([a-z]+)/.exec(block)?.[1]
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1]
    const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1]
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]
    if (!family || !style || !weight || !url || !unicodeRange) {
      throw new Error(`Could not parse @font-face block for subset ${subset}`)
    }
    faces.push({ family, style, weight, url, unicodeRange: unicodeRange.trim() })
  }
  return faces
}

async function main(): Promise<void> {
  const faces: FontFace[] = []
  for (const cssUrl of FAMILY_CSS_URLS) {
    const css = (await fetchBuffer(cssUrl)).toString('utf8')
    const latinFaces = parseLatinFaces(css)
    if (latinFaces.length === 0) {
      throw new Error(`No latin @font-face blocks found in ${cssUrl}`)
    }
    faces.push(...latinFaces)
  }

  const downloads = new Map<string, Buffer>()
  for (const face of faces) {
    if (!downloads.has(face.url)) {
      downloads.set(face.url, await fetchBuffer(face.url))
    }
  }

  const rules = faces.map(face => {
    const woff2 = downloads.get(face.url)
    if (!woff2) throw new Error(`Missing download for ${face.url}`)
    const base64 = woff2.toString('base64')
    return (
      `@font-face{font-family:'${face.family}';font-style:${face.style};` +
      `font-weight:${face.weight};src:url(data:font/woff2;base64,${base64}) ` +
      `format('woff2');unicode-range:${face.unicodeRange}}`
    )
  })

  const summary = faces
    .map(face => `${face.family} ${face.weight} ${face.style} (${downloads.get(face.url)?.length ?? 0} bytes)`)
    .join(', ')

  const fileContent = `// Voucher card fonts, embedded as base64 data-URI @font-face rules so card
// rendering never depends on a CDN (spec section 6, F24). All faces are SIL
// OFL licensed; latin subsets only.
// Generated by scripts/vouchers/fetch-fonts.ts. Do not edit by hand.
// Faces: ${summary}
// Server-side print pipeline only; never import from client components.

export const VOUCHER_FONTS_SELF_HOSTED = true

// Populated only in the Google Fonts fallback mode (self-hosted fonts absent).
export const VOUCHER_CARD_FONT_LINKS_HTML = ''

export const VOUCHER_CARD_FONT_FACE_CSS = \`${rules.join('\n')}\`
`

  writeFileSync(OUTPUT_PATH, fileContent, 'utf8')
  console.warn(`Wrote ${OUTPUT_PATH} with ${faces.length} @font-face rules: ${summary}`)
}

main().catch(error => {
  console.error('fetch-fonts failed, card-fonts.ts not written:', error instanceof Error ? error.message : error)
  process.exit(1)
})
