/**
 * The arithmetic behind the refund sentence a guest is shown when they pay a seasonal deposit.
 *
 * Until now that sentence was generated by `describeRefundPolicy`, served to the website by
 * /api/table-bookings/periods, and enforced by nothing at all. This is the enforcement.
 *
 * THE RULE, owner-confirmed 2026-07-30
 *
 *   Full refund up to N days before the booking date. Inside N days, nothing. N is the period's
 *   own `refund_cutoff_days`, SNAPSHOT onto the booking at creation, so editing or archiving the
 *   period later cannot change the promise a guest already has.
 *
 * WHOLE DAYS, IN LONDON, AGAINST THE BOOKING DATE. Three deliberate choices, each of which has a
 * wrong answer that looks right:
 *
 *   1. WHOLE DAYS, not elapsed hours. The promise says "7 days before the booking date", so the
 *      guest owns the whole of that day. Cancelling at 9am on the day seven days out is a full
 *      refund, and so is cancelling at 11:59pm the same evening. Measuring 7 x 24 hours from the
 *      booking instead would refuse someone on the very day we told them was fine, which is the
 *      worse of the two failures and would also be a regression against the tiering that has been
 *      live in `calculateRefundTier` for months.
 *   2. EUROPE/LONDON, not the server's clock. Vercel runs in UTC. Between midnight and 1am BST the
 *      server's calendar date is still yesterday, so a UTC day count moves this money boundary by a
 *      whole day for an hour every night through the summer.
 *   3. CALENDAR DAYS, not milliseconds divided by 86,400,000. The last Sunday in March is 23 hours
 *      long and the last Sunday in October is 25. A subtraction across either gives 6.96 or 7.04
 *      days, and whichever way the code rounds, one of the two clock changes silently moves the
 *      cutoff. Both are covered by tests.
 *
 * Pure: no clock, no database, no environment. `now` is passed in, which is the only reason the
 * boundary cases below can be asserted at all.
 */

import { toLocalIsoDate } from '@/lib/dateUtils'

const MS_PER_DAY = 24 * 60 * 60 * 1000
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

export type SeasonalRefundDecision = {
  /** True when the guest is inside the full-refund window the period promised them. */
  entitled: boolean
  /** What to refund, in pounds. The seasonal promise is all or nothing, never a proportion. */
  amount: number
  /** Whole London days from today to the booking date. Negative once the booking date has passed. */
  daysBefore: number
  cutoffDays: number
  /** Plain-English explanation, safe to show staff and to store on an audit row. */
  reason: string
}

/** Whole calendar days between two YYYY-MM-DD dates. No timezone maths: both are already dates. */
function calendarDaysBetween(fromIsoDate: string, toIsoDate: string): number {
  const from = Date.parse(`${fromIsoDate}T00:00:00Z`)
  const to = Date.parse(`${toIsoDate}T00:00:00Z`)
  return Math.round((to - from) / MS_PER_DAY)
}

/**
 * Decides what a seasonal deposit is entitled to be refunded right now.
 *
 * `refundCutoffDays` of 0 means the deposit was never refundable, which the settings screen allows
 * and `describeRefundPolicy` already words differently. A manager waiver is NOT modelled here: it
 * overrides this answer at the call site, and is audited there, because "the rule said no and a
 * named manager overrode it" is the thing that has to be on the record.
 */
export function resolveSeasonalDepositRefund(input: {
  /** The booking date as YYYY-MM-DD. */
  bookingDate: string
  /** The booking's SNAPSHOT `deposit_refund_cutoff_days`, never the period's current value. */
  refundCutoffDays: number
  /** The deposit actually paid, in pounds. */
  depositAmount: number
  now?: Date
}): SeasonalRefundDecision {
  const { bookingDate, refundCutoffDays, depositAmount } = input
  const now = input.now ?? new Date()

  const cutoffDays = Number.isFinite(refundCutoffDays) ? Math.max(0, Math.trunc(refundCutoffDays)) : 0
  const amount = Number.isFinite(depositAmount) ? Math.max(0, Math.round(depositAmount * 100) / 100) : 0

  if (!ISO_DATE.test(bookingDate)) {
    // A malformed date must never be read as "miles away, refund it all".
    return {
      entitled: false,
      amount: 0,
      daysBefore: 0,
      cutoffDays,
      reason: 'The booking date could not be read, so no automatic refund was worked out.',
    }
  }

  const daysBefore = calendarDaysBetween(toLocalIsoDate(now), bookingDate)

  if (cutoffDays <= 0) {
    return {
      entitled: false,
      amount: 0,
      daysBefore,
      cutoffDays,
      reason: 'This deposit was never refundable, though a manager may still waive that.',
    }
  }

  if (daysBefore >= cutoffDays) {
    return {
      entitled: true,
      amount,
      daysBefore,
      cutoffDays,
      reason:
        `Cancelled ${daysBefore} days before the booking, which is ${cutoffDays} days or more, ` +
        'so the deposit is refunded in full.',
    }
  }

  return {
    entitled: false,
    amount: 0,
    daysBefore,
    cutoffDays,
    reason:
      `Cancelled ${daysBefore} days before the booking, which is inside the ${cutoffDays}-day ` +
      'window, so the deposit is not refunded. A manager may waive that.',
  }
}

/**
 * The booking fields this rule needs. Deliberately narrow so it works against a partial select, and
 * deliberately reading only SNAPSHOT columns: `booking_periods` is mutable and a booking taken in
 * November must not be re-judged against a period edited in January.
 */
export type BookingForSeasonalRefund = {
  booking_date: string
  deposit_refund_cutoff_days?: number | null
  booking_period_code?: string | null
}

/**
 * True when this booking carries a seasonal refund promise, so the all-or-nothing rule above
 * governs it rather than the legacy sliding tier. A booking with no snapshot is an ordinary
 * large-group deposit and keeps the behaviour it has always had.
 */
export function hasSeasonalRefundTerms(booking: BookingForSeasonalRefund): boolean {
  return booking.deposit_refund_cutoff_days !== null && booking.deposit_refund_cutoff_days !== undefined
}
