import { beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('next/cache', () => ({
  revalidatePath: vi.fn(),
  revalidateTag: vi.fn(),
}))

vi.mock('@/app/actions/rbac', () => ({
  checkUserPermission: vi.fn(),
}))

vi.mock('@/app/actions/audit', () => ({
  logAuditEvent: vi.fn(),
}))

vi.mock('@/lib/supabase/server', () => ({
  createClient: vi.fn(),
}))

vi.mock('@/lib/supabase/admin', () => ({
  createAdminClient: vi.fn(),
}))

import { checkUserPermission } from '@/app/actions/rbac'
import { createAdminClient } from '@/lib/supabase/admin'
import { getOjInvoiceReissuePreview } from '../invoice-reissue'

const mockedPermission = vi.mocked(checkUserPermission)
const mockedCreateAdminClient = vi.mocked(createAdminClient)

const SOURCE_INVOICE_ID = '00000000-0000-4000-8000-000000000001'
const VENDOR_ID = '00000000-0000-4000-8000-000000000002'

type QueryResult = { data?: unknown; error?: { message: string } | null; count?: number | null }

function makeQuery(result: QueryResult) {
  const chain: any = {
    select: vi.fn(() => chain),
    eq: vi.fn(() => chain),
    is: vi.fn(() => chain),
    gte: vi.fn(() => chain),
    lte: vi.fn(() => chain),
    lt: vi.fn(() => chain),
    order: vi.fn(() => chain),
    limit: vi.fn(() => chain),
    maybeSingle: vi.fn().mockResolvedValue(result),
    single: vi.fn().mockResolvedValue(result),
    then: (resolve: (value: QueryResult) => unknown, reject?: (reason: unknown) => unknown) =>
      Promise.resolve(result).then(resolve, reject),
  }
  return chain
}

function makeInvoice(overrides: Record<string, unknown> = {}) {
  return {
    id: SOURCE_INVOICE_ID,
    invoice_number: 'INV-003W0',
    vendor_id: VENDOR_ID,
    invoice_date: '2026-06-01',
    due_date: '2026-06-08',
    reference: 'OJ Projects 2026-05',
    status: 'sent',
    invoice_discount_percentage: 0,
    total_amount: 120,
    paid_amount: 0,
    notes: 'OJ Projects timesheet',
    internal_notes: 'Auto-generated by OJ Projects billing run',
    vendor: { name: 'Barons Pubs' },
    ...overrides,
  }
}

function makeAdminClient(options: {
  invoice?: Record<string, unknown>
  paymentsCount?: number
  entries?: unknown[]
  olderEntries?: unknown[]
  activeCharges?: unknown[]
  recurringInstances?: unknown[]
  sourceRecurringInstances?: unknown[]
}) {
  const tableCounts: Record<string, number> = {}
  const admin = {
    from: vi.fn((table: string) => {
      tableCounts[table] = (tableCounts[table] || 0) + 1

      if (table === 'invoices') {
        return makeQuery({ data: options.invoice || makeInvoice(), error: null })
      }

      if (table === 'invoice_payments') {
        return makeQuery({ count: options.paymentsCount || 0, error: null })
      }

      if (table === 'oj_vendor_billing_settings') {
        return makeQuery({
          data: {
            hourly_rate_ex_vat: 75,
            mileage_rate: 0.55,
            vat_rate: 20,
            statement_mode: false,
          },
          error: null,
        })
      }

      if (table === 'oj_entries') {
        return makeQuery({
          data: tableCounts[table] === 1 ? options.entries || [] : options.olderEntries || [],
          error: null,
        })
      }

      if (table === 'oj_vendor_recurring_charges') {
        return makeQuery({ data: options.activeCharges || [], error: null })
      }

      if (table === 'oj_recurring_charge_instances') {
        return makeQuery({
          data: tableCounts[table] === 1 ? options.recurringInstances || [] : options.sourceRecurringInstances || [],
          error: null,
        })
      }

      throw new Error(`Unexpected table: ${table}`)
    }),
  }

  return admin
}

describe('OJ invoice reissue preview', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockedPermission.mockResolvedValue(true)
  })

  it('blocks paid OJ invoices', async () => {
    mockedCreateAdminClient.mockReturnValue(makeAdminClient({
      invoice: makeInvoice({ status: 'paid', paid_amount: 120 }),
    }) as any)

    const preview = await getOjInvoiceReissuePreview(SOURCE_INVOICE_ID)

    expect(preview.eligible).toBe(false)
    expect(preview.error).toContain('Paid, partially paid, and written off invoices cannot be reissued')
  })

  it('includes active recurring charges and excludes disabled source-linked recurring charges', async () => {
    mockedCreateAdminClient.mockReturnValue(makeAdminClient({
      entries: [
        {
          id: 'entry-1',
          entry_type: 'time',
          entry_date: '2026-05-07',
          project_id: 'project-1',
          duration_minutes_rounded: 60,
          miles: null,
          hourly_rate_ex_vat_snapshot: 75,
          vat_rate_snapshot: 20,
          mileage_rate_snapshot: null,
          amount_ex_vat_snapshot: null,
          billable: true,
          description: 'Marketing Meeting',
          work_type_name_snapshot: 'Consulting',
          status: 'billed',
          invoice_id: SOURCE_INVOICE_ID,
          project: { project_code: 'OJP-BP-RET-202605', project_name: 'Barons Pubs - Retainer (May 2026)' },
          work_type: { name: 'Consulting' },
          invoice: { id: SOURCE_INVOICE_ID, invoice_number: 'INV-003W0', status: 'sent' },
        },
      ],
      olderEntries: [{ id: 'old-entry', entry_date: '2026-04-30' }],
      activeCharges: [
        {
          id: 'charge-active',
          description: 'EventHub Monthly Hosting',
          amount_ex_vat: 100,
          vat_rate: 20,
          sort_order: 1,
          frequency: 'monthly',
          is_active: true,
          created_at: '2026-01-01T00:00:00Z',
        },
        {
          id: 'charge-disabled',
          description: 'Disabled Hosting',
          amount_ex_vat: 30,
          vat_rate: 20,
          sort_order: 2,
          frequency: 'monthly',
          is_active: false,
          created_at: '2026-01-01T00:00:00Z',
        },
      ],
      sourceRecurringInstances: [
        {
          id: 'recurring-disabled',
          vendor_id: VENDOR_ID,
          recurring_charge_id: 'charge-disabled',
          period_yyyymm: '2026-05',
          period_start: '2026-05-01',
          period_end: '2026-05-31',
          description_snapshot: 'Disabled Hosting',
          amount_ex_vat_snapshot: 30,
          vat_rate_snapshot: 20,
          sort_order_snapshot: 2,
          status: 'billed',
          invoice_id: SOURCE_INVOICE_ID,
          created_at: '2026-05-01T00:00:00Z',
          recurring_charge: { is_active: false },
          invoice: { id: SOURCE_INVOICE_ID, invoice_number: 'INV-003W0', status: 'sent' },
        },
      ],
    }) as any)

    const preview = await getOjInvoiceReissuePreview(SOURCE_INVOICE_ID)

    expect(preview.eligible).toBe(true)
    if (!preview.eligible) return

    expect(preview.includedEntries).toHaveLength(1)
    expect(preview.includedRecurring.map((item) => item.description)).toEqual(['EventHub Monthly Hosting'])
    expect(preview.includedRecurring[0].is_virtual).toBe(true)
    expect(preview.excludedRecurring).toEqual([
      expect.objectContaining({
        description: 'Disabled Hosting',
        reason: 'Recurring charge disabled',
      }),
    ])
    expect(preview.warnings).toEqual([
      '1 older unbilled OJ entry is excluded because this reissue is month-only.',
    ])
    expect(preview.lineItems.map((item) => item.description)).toContain('EventHub Monthly Hosting')
  })
})
