#!/bin/bash

echo "=== Google Calendar Sync Fix Script ==="
echo ""
echo "Current Node.js version:"
node --version
echo ""

# Check if nvm is installed
if command -v nvm &> /dev/null; then
    echo "✓ nvm is installed"
    echo ""
    echo "To fix Google Calendar sync, you need to switch to Node.js v20:"
    echo ""
    echo "Run these commands:"
    echo "  nvm install 20"
    echo "  nvm use 20"
    echo "  npm install"
    echo ""
    echo "Then test with:"
    echo "  npx tsx scripts/test-calendar-sync.ts"
elif command -v fnm &> /dev/null; then
    echo "✓ fnm is installed"
    echo ""
    echo "To fix Google Calendar sync, you need to switch to Node.js v20:"
    echo ""
    echo "Run these commands:"
    echo "  fnm install 20"
    echo "  fnm use 20"
    echo "  npm install"
    echo ""
    echo "Then test with:"
    echo "  npx tsx scripts/test-calendar-sync.ts"
else
    echo "⚠️  No Node version manager detected"
    echo ""
    echo "To fix Google Calendar sync, you need Node.js v20."
    echo ""
    echo "Install nvm first:"
    echo "  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
    echo ""
    echo "Then restart your terminal and run:"
    echo "  nvm install 20"
    echo "  nvm use 20"
    echo "  npm install"
fi

echo ""
echo "=== Alternative Workarounds ==="
echo ""
echo "If you must use Node.js v22, you can try:"
echo ""
echo "1. Run dev server with legacy provider:"
echo "   npm run dev:legacy"
echo ""
echo "2. Or set .nvmrc to automatically use Node.js 20:"
echo "   echo '20' > .nvmrc"
echo "   nvm use"
echo ""
echo "Note: Production (Vercel) will use Node.js 20 automatically"
echo "due to the 'engines' setting in package.json."