-- Capture the contents of the two accessibility backup tables before dropping
-- them. Read only. This capture IS the rollback: run it, store the output, and
-- only then apply
-- supabase/migrations/20260910133000_drop_accessibility_backup_tables.sql.
--
-- Run against production (project ref tfcasgxopxegwrabvwat) through the
-- Supabase MCP execute_sql tool. Save the output of each query into
-- tasks/accessibility-backup-tables/captured-2026MMDD/ and commit it, alongside
-- the column listing from preflight.sql query 4. Both tables are expected to be
-- small page copy, so committing the JSON is reasonable; if either turns out to
-- hold personal data, store it outside the repository instead and note where in
-- the packet.

-- 1. Every row of the copy table, as JSON.
select coalesce(jsonb_pretty(jsonb_agg(t order by t::text)), '[]')
from public.backup_accessibility_copy_20260906 t;

-- 2. Every row of the FAQ table, as JSON.
select coalesce(jsonb_pretty(jsonb_agg(t order by t::text)), '[]')
from public.backup_accessibility_faq_20260906 t;

-- 3. A CREATE TABLE shape for each, so a restore does not have to be guessed
--    from the JSON. Paste the result into the captured folder as schema.sql.
--
--    This handles identity and generated columns explicitly. Emitting a
--    generated column's expression as an ordinary DEFAULT, or dropping an
--    identity clause, produces SQL that restores the WRONG table: verified on
--    PostgreSQL 16, where a naive version of this query turned
--    `slug text generated always as (lower(section)) stored` into
--    `slug text default lower(section)`, and silently reduced an identity
--    column to a NOT NULL column with no default, so inserts would fail.
--
--    Column shape only. Constraints come from query 4, which you need as well.
--    If you have direct psql access to production rather than only the MCP,
--    prefer `pg_dump --schema-only --table=public.backup_accessibility_copy_20260906
--    --table=public.backup_accessibility_faq_20260906` over queries 3, 4 and 5:
--    it is the tool built for exactly this and cannot drift the way hand-rolled
--    catalogue SQL can. These queries exist for the MCP-only path.
select 'create table public.' || c.relname || ' (' || string_agg(
         quote_ident(a.attname) || ' ' ||
         format_type(a.atttypid, a.atttypmod) ||
         case when a.attnotnull then ' not null' else '' end ||
         case
           when a.attidentity = 'a' then ' generated always as identity'
           when a.attidentity = 'd' then ' generated by default as identity'
           when a.attgenerated = 's'
             then ' generated always as (' ||
                  pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
           else coalesce(' default ' || pg_get_expr(ad.adbin, ad.adrelid), '')
         end,
         ', ' order by a.attnum
       ) || ');' as create_statement
from pg_class c
join pg_namespace n  on n.oid = c.relnamespace
join pg_attribute a  on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
where n.nspname = 'public'
  and c.relname in ('backup_accessibility_copy_20260906',
                    'backup_accessibility_faq_20260906')
group by c.relname
order by c.relname;

-- 4. Constraints. Query 3 captures column shape only, so without this a restore
--    silently loses the primary key, and any unique, check or foreign-key
--    constraint. Query 5 does not cover the gap: an index definition restores a
--    primary key as a plain unique index, which is not the same object.
--    Apply these as ALTER TABLE ... ADD CONSTRAINT after the create statements.
select conrelid::regclass::text as table_name,
       conname,
       case contype when 'p' then 'primary key'
                    when 'u' then 'unique'
                    when 'c' then 'check'
                    when 'f' then 'foreign key'
                    when 'x' then 'exclusion'
                    else contype::text end as kind,
       'alter table ' || conrelid::regclass::text ||
       ' add constraint ' || quote_ident(conname) || ' ' ||
       pg_get_constraintdef(oid) || ';' as restore_statement
from pg_constraint
where conrelid in ('public.backup_accessibility_copy_20260906'::regclass,
                   'public.backup_accessibility_faq_20260906'::regclass)
order by 1, 3, 2;

-- 5. Indexes that are NOT backing a constraint. The constraint-backed ones are
--    recreated by query 4's statements, so applying both would fail on a
--    duplicate name. This excludes them.
select i.tablename, i.indexname, i.indexdef
from pg_indexes i
join pg_class ic on ic.relname = i.indexname
join pg_namespace ins on ins.oid = ic.relnamespace and ins.nspname = i.schemaname
where i.schemaname = 'public'
  and i.tablename in ('backup_accessibility_copy_20260906',
                      'backup_accessibility_faq_20260906')
  and not exists (select 1 from pg_constraint c where c.conindid = ic.oid)
order by i.tablename, i.indexname;

-- 6. Table and column comments, if either table carries any.
select c.relname as table_name,
       null::text as column_name,
       obj_description(c.oid, 'pg_class') as comment
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname in ('backup_accessibility_copy_20260906',
                    'backup_accessibility_faq_20260906')
  and obj_description(c.oid, 'pg_class') is not null
union all
select c.relname, a.attname, col_description(c.oid, a.attnum)
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
where n.nspname = 'public'
  and c.relname in ('backup_accessibility_copy_20260906',
                    'backup_accessibility_faq_20260906')
  and col_description(c.oid, a.attnum) is not null
order by 1, 2 nulls first;
