-- =============================================================
-- Migration: Import Historical Data from Excel Spreadsheets
-- Generated by: scripts/import-historical-data.py
-- Generated at: 2026-04-05T11:19:58.707142
-- =============================================================
-- Data sources:
--   1. Mileage Tracker - 2025.xlsx (Oct-Dec, 68 trips)
--   2. Petty Cash - 2025.xlsx (Jan-Dec, expenses)
--   3. Machine Games Duty Collections (New).xlsm (collections + returns)
-- =============================================================

-- =============================================================
-- Mileage Trips (historical import: Oct-Dec 2025)
-- =============================================================

-- Insert any destinations not already seeded
INSERT INTO public.mileage_destinations (name) SELECT 'B&Q Hayes' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'B&Q Hayes');
INSERT INTO public.mileage_destinations (name) SELECT 'Bookers' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Bookers');
INSERT INTO public.mileage_destinations (name) SELECT 'Costco' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Costco');
INSERT INTO public.mileage_destinations (name) SELECT 'Ikea Reading' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Ikea Reading');
INSERT INTO public.mileage_destinations (name) SELECT 'Screwfix TW4' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Screwfix TW4');
INSERT INTO public.mileage_destinations (name) SELECT 'Tesco - Ashford' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Tesco - Ashford');
INSERT INTO public.mileage_destinations (name) SELECT 'Two Rivers Car Park' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park');
INSERT INTO public.mileage_destinations (name) SELECT 'Westfield' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Westfield');

-- Insert trips and their legs
DO $$
DECLARE
  v_trip_id UUID;
  v_anchor_id UUID;
  v_dest_id UUID;
BEGIN
  -- Get the Anchor (home base) destination ID
  SELECT id INTO v_anchor_id FROM public.mileage_destinations WHERE is_home_base = TRUE LIMIT 1;

  -- Trip 1: 2025-10-01 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-01', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 2: 2025-10-01 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-01', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 3: 2025-10-07 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-07', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 4: 2025-10-07 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-07', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 5: 2025-10-08 -> Screwfix TW4 (11.0 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Screwfix TW4' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-08', 'Screwfix TW4', 11.0, 11.0, 0, 4.95, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 5.5);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 5.5);

  -- Trip 6: 2026-10-15 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2026-10-15', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 7: 2025-10-16 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-16', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 8: 2025-10-16 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-16', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 9: 2025-10-17 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-17', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 10: 2025-10-17 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-17', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 11: 2025-10-18 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-18', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 12: 2025-10-18 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-18', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 13: 2025-10-18 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-18', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 14: 2025-10-20 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-20', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 15: 2025-10-21 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-21', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 16: 2025-10-22 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-22', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 17: 2025-10-22 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-22', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 18: 2025-10-24 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-24', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 19: 2025-10-25 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-25', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 20: 2025-10-28 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-28', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 21: 2025-10-28 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-28', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 22: 2025-10-29 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-10-29', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 23: 2025-11-01 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-01', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 24: 2025-11-03 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-03', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 25: 2025-11-04 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-04', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 26: 2025-11-05 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-05', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 27: 2025-11-05 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-05', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 28: 2025-11-06 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-06', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 29: 2025-11-06 -> B&Q Hayes (34.0 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'B&Q Hayes' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-06', 'B&Q Hayes', 34.0, 34.0, 0, 15.30, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 17.0);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 17.0);

  -- Trip 30: 2025-11-07 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-07', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 31: 2025-11-07 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-07', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 32: 2025-11-08 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-08', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 33: 2025-11-10 -> Westfield (32.0 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Westfield' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-10', 'Westfield', 32.0, 32.0, 0, 14.40, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 16.0);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 16.0);

  -- Trip 34: 2025-11-11 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-11', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 35: 2025-11-12 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-12', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 36: 2025-11-13 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-13', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 37: 2025-11-13 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-13', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 38: 2025-11-13 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-13', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 39: 2025-11-15 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-15', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 40: 2025-11-10 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-11-10', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 41: 2025-12-01 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-01', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 42: 2025-12-02 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-02', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 43: 2025-12-03 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-03', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 44: 2025-12-04 -> Ikea Reading (62.0 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Ikea Reading' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-04', 'Ikea Reading', 62.0, 62.0, 0, 27.90, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 31.0);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 31.0);

  -- Trip 45: 2025-12-04 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-04', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 46: 2025-12-05 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-05', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 47: 2025-12-05 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-05', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 48: 2025-12-06 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-06', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 49: 2025-12-08 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-08', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 50: 2025-12-09 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-09', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 51: 2025-12-10 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-10', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 52: 2025-12-10 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-10', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 53: 2025-12-10 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-10', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 54: 2025-12-11 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-11', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 55: 2025-12-11 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-11', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 56: 2025-12-12 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-12', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 57: 2025-12-13 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-13', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 58: 2025-12-18 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-18', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 59: 2025-12-18 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-18', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 60: 2025-12-19 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-19', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 61: 2025-12-20 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-20', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 62: 2025-12-22 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-22', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 63: 2025-12-24 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-24', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 64: 2025-12-24 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-24', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 65: 2025-12-28 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-28', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 66: 2025-12-29 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-29', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 67: 2025-12-30 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-30', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 68: 2025-12-30 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2025-12-30', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

END;
$$;

-- =============================================================
-- Expenses (historical import: Jan-Dec 2025)
-- =============================================================

INSERT INTO public.expenses (expense_date, company_ref, justification, amount, vat_applicable, vat_amount, created_by) VALUES
  ('2025-01-08', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-01-09', 'Tesco', 'Groceries', 1.39, FALSE, 0.00, NULL),
  ('2025-01-10', 'Tesco', 'Groceries', 14.20, FALSE, 0.00, NULL),
  ('2025-01-11', 'Tamarra Lounge', 'Meeting', 168.75, FALSE, 0.00, NULL),
  ('2025-01-12', 'Tesco', 'Groceries', 1.45, FALSE, 0.00, NULL),
  ('2025-01-14', 'Tesco', 'Groceries', 4.78, FALSE, 0.00, NULL),
  ('2025-01-17', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-01-20', 'Mr Fizz', 'Gas', 63.00, TRUE, 10.50, NULL),
  ('2025-01-21', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-01-23', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-01-24', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-01-25', 'Mandy Jones', 'Christmas work meal didn’t go open pub', 35.00, FALSE, 0.00, NULL),
  ('2025-01-25', 'Bombay Story', 'Meeting', 189.65, FALSE, 0.00, NULL),
  ('2025-01-25', 'Tesco', 'Groceries', 4.98, FALSE, 0.00, NULL),
  ('2025-01-28', 'T5 Stores', 'Groceries', 4.69, FALSE, 0.00, NULL),
  ('2025-01-29', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-01-30', 'Tesco', 'Groceries', 12.20, FALSE, 0.00, NULL),
  ('2025-01-31', 'Tesco', 'Groceries', 1.98, FALSE, 0.00, NULL),
  ('2025-01-31', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-02-04', 'Tesco', 'Groceries', 5.50, FALSE, 0.00, NULL),
  ('2025-02-05', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-02-05', 'T5 Store', 'Groceries', 8.78, FALSE, 0.00, NULL),
  ('2025-02-07', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-02-07', 'Tesco', 'Groceries', 22.84, FALSE, 0.00, NULL),
  ('2025-02-09', 'Tesco', 'Groceries', 26.29, FALSE, 0.00, NULL),
  ('2025-02-11', 'tesco', 'Groceries', 2.19, FALSE, 0.00, NULL),
  ('2025-02-13', 'Tesco', 'Groceries', 13.90, FALSE, 0.00, NULL),
  ('2025-02-13', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-02-14', 'Tesco', 'Groceries', 2.70, FALSE, 0.00, NULL),
  ('2025-02-14', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-02-15', 'Tesco', 'Groceries', 9.74, FALSE, 0.00, NULL),
  ('2025-02-17', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-02-17', 'Mr Fizz', 'Gas', 65.50, TRUE, 10.92, NULL),
  ('2025-02-18', 'Tesco', 'Groceries', 13.60, FALSE, 0.00, NULL),
  ('2025-02-21', 'Tesco', 'Groceries', 3.69, FALSE, 0.00, NULL),
  ('2025-02-21', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-02-21', 'Nikki', 'Game Show', 125.00, FALSE, 0.00, NULL),
  ('2025-02-22', 'New Bettola', 'Team', 186.18, FALSE, 0.00, NULL),
  ('2025-02-22', 'Tesco', 'Groceries', 24.25, FALSE, 0.00, NULL),
  ('2025-02-23', 'T5 Store', 'Groceries', 2.99, FALSE, 0.00, NULL),
  ('2025-02-24', 'Garsons', 'Prizes', 75.98, FALSE, 0.00, NULL),
  ('2025-02-24', 'Garsons The Orangery', 'Lunch', 26.90, TRUE, 4.48, NULL),
  ('2025-02-25', 'Tesco', 'Groceries', 10.12, FALSE, 0.00, NULL),
  ('2025-02-27', 'T5 Store', 'Groceries', 2.84, FALSE, 0.00, NULL),
  ('2025-02-27', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-02-27', 'Tesco', 'Groceries', 13.57, FALSE, 0.00, NULL),
  ('2025-02-27', 'T5 Store', 'Groceries', 2.84, FALSE, 0.00, NULL),
  ('2025-02-28', 'T5 Store', 'Groceries', 2.50, FALSE, 0.00, NULL),
  ('2025-02-28', 'T5 Store', 'Groceries', 2.50, FALSE, 0.00, NULL),
  ('2025-02-28', 'Yasmin', 'Cleaner', 96.00, FALSE, 0.00, NULL),
  ('2025-02-28', 'Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-03-03', 'Amazon (Mandy)', 'Window Dec', 27.93, FALSE, 0.00, NULL),
  ('2025-03-04', 'Tesco', 'Groceries', 2.75, FALSE, 0.00, NULL),
  ('2025-03-04', 'Tesco', 'Groceries', 12.57, FALSE, 0.00, NULL),
  ('2025-03-05', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-03-06', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-03-06', 'Pets at Home', 'Dog Biscuits', 3.50, FALSE, 0.00, NULL),
  ('2025-03-06', 'Ansell Garden Centre', 'Gift for team birthday/Plant for pub', 33.98, TRUE, 5.66, NULL),
  ('2025-03-07', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-03-07', 'Tesco', 'Groceries', 7.60, FALSE, 0.00, NULL),
  ('2025-03-09', 'T5 Stores', 'Stationary', 2.50, FALSE, 0.00, NULL),
  ('2025-03-12', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-03-14', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-03-14', 'Spring Tasting Events', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-03-16', 'T5 Stores', 'Groceries', 2.99, FALSE, 0.00, NULL),
  ('2025-03-17', 'Mr Fizz', 'Gas', 17.50, TRUE, 17.50, NULL),
  ('2025-03-20', 'Tesco', 'Groceries', 7.33, FALSE, 0.00, NULL),
  ('2025-03-21', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-03-21', 'Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-03-21', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-03-23', 'Keith Taylor', 'Garden Bench', 30.00, FALSE, 0.00, NULL),
  ('2025-03-24', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-03-28', 'Nikki', 'Gameshow host', 125.00, FALSE, 0.00, NULL),
  ('2025-03-28', 'Yasmin', 'Cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-03-28', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-03-31', 'Mr Fizz', 'Gas', 21.00, TRUE, 3.50, NULL),
  ('2025-04-01', 'Tesco', 'Groceries', 5.89, FALSE, 0.00, NULL),
  ('2025-04-02', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-04-04', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-04-04', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-04-06', 'Two Rivers Car Park', 'Parking', 2.00, FALSE, 0.00, NULL),
  ('2025-04-07', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-04-08', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-04-12', 'Tesco', 'Groceries', 2.49, FALSE, 0.00, NULL),
  ('2025-04-12', 'M AND S', 'Groceries', 5.60, FALSE, 0.00, NULL),
  ('2025-04-16', 'Tesco', 'Groceries', 4.59, FALSE, 0.00, NULL),
  ('2025-04-21', 'Tesco', 'Groceries', 2.49, FALSE, 0.00, NULL),
  ('2025-04-23', 'Tesco', 'Groceries', 34.12, FALSE, 0.00, NULL),
  ('2025-04-24', 'Tesco', 'Groceries', 5.30, FALSE, 0.00, NULL),
  ('2025-04-24', 'Dan', 'Gardening and car park tidy', 250.00, FALSE, 0.00, NULL),
  ('2025-04-25', 'Tesco', 'Groceries', 1.10, FALSE, 0.00, NULL),
  ('2025-04-25', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-04-25', 'Cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-04-27', 'T5 Stores', 'Groceries', 1.29, FALSE, 0.00, NULL),
  ('2025-05-01', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-05-02', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-05-05', 'Bank Hoilday Karaoke', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-05-06', 'T5 Stores', 'Groceries', 3.64, FALSE, 0.00, NULL),
  ('2025-05-06', 'Notcutts Garden Centre', 'mixer tap', 11.99, FALSE, 0.00, NULL),
  ('2025-05-07', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-05-08', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-05-08', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-05-08', 'Sing Along Karaoke', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-05-09', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-05-11', 'T5 Stores', 'Groceries', 1.75, FALSE, 0.00, NULL),
  ('2025-05-12', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2025-05-14', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-05-15', 'Tesco', 'Groceries', 10.41, FALSE, 0.00, NULL),
  ('2025-05-16', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-05-17', 'Tesco', 'Groceries', 4.18, FALSE, 0.00, NULL),
  ('2025-05-17', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-05-18', 'T5 Stores', 'Groceries', 1.90, FALSE, 0.00, NULL),
  ('2025-05-20', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-05-20', 'Halfords', 'Cable', 12.00, FALSE, 0.00, NULL),
  ('2025-05-23', 'Tesco', 'Groceries', 2.76, FALSE, 0.00, NULL),
  ('2025-05-23', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-05-23', 'cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-05-25', 'Bank Hoilday Karaoke', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-05-29', 'Tesco', 'Groceries', 2.39, FALSE, 0.00, NULL),
  ('2025-05-30', 'Yasmin', 'cleaner', 48.00, FALSE, 0.00, NULL),
  ('2025-05-31', 'Tesco', 'Groceries', 25.67, FALSE, 0.00, NULL),
  ('2025-05-29', 'Poundland', 'Prizes for nikki', 8.00, FALSE, 0.00, NULL),
  ('2025-06-03', 'Tesco', 'Groceries', 10.37, FALSE, 0.00, NULL),
  ('2025-06-04', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-06-04', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-06-10', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-06-10', 'T.K.Maxx', 'Kitchenwear', 9.99, FALSE, 0.00, NULL),
  ('2025-06-12', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-06-12', 'Hayes Food Centre', 'Groceries', 15.21, FALSE, 0.00, NULL),
  ('2025-06-12', 'Wickes', 'Double sided tape', 9.50, FALSE, 0.00, NULL),
  ('2025-06-13', 'Rum Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-06-13', 'T5 Stores', 'Groceries', 4.00, FALSE, 0.00, NULL),
  ('2025-06-16', 'Tesco', 'Groceries', 7.08, FALSE, 0.00, NULL),
  ('2025-06-18', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-06-20', 'Cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-06-21', 'Tesco', 'Groceries', 3.85, FALSE, 0.00, NULL),
  ('2025-06-23', 'Mr Fizz', 'Gas', 63.00, TRUE, 10.50, NULL),
  ('2025-06-25', 'Tesco', 'Groceries', 6.19, FALSE, 0.00, NULL),
  ('2025-06-26', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-06-27', 'Nikki Drag Night', 'Host', 125.00, FALSE, 0.00, NULL),
  ('2025-06-07', 'Tesco', 'Groceries', 21.62, FALSE, 0.00, NULL),
  ('2025-07-02', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-07-02', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-07-03', 'Poundland', 'sweets', 9.50, FALSE, 0.00, NULL),
  ('2025-07-04', 'Tesco', 'Groceries', 44.07, FALSE, 0.00, NULL),
  ('2025-07-05', 'Tesco', 'Groceries', 22.63, FALSE, 0.00, NULL),
  ('2025-07-08', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-07-09', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-07-09', 'Tesco', 'Groceries', 4.95, FALSE, 0.00, NULL),
  ('2025-07-12', 'Tesco', 'Groceries', 16.65, FALSE, 0.00, NULL),
  ('2025-07-13', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-07-16', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-07-18', 'Tesco', 'Groceries', 9.00, FALSE, 0.00, NULL),
  ('2025-07-18', 'Cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-07-19', 'Tesco', 'Groceries', 31.97, FALSE, 0.00, NULL),
  ('2025-07-20', 'T5 Stores', 'Batteries', 3.99, FALSE, 0.00, NULL),
  ('2025-07-21', 'T5 Stores', 'Groceries', 1.90, FALSE, 0.00, NULL),
  ('2025-07-21', 'Mr Fizz', 'Gas', 63.00, TRUE, 10.50, NULL),
  ('2025-07-25', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-07-25', 'Nikki Sports day', 'Host', 125.00, FALSE, 0.00, NULL),
  ('2025-07-25', 'T5 Stores', 'Groceries', 3.50, FALSE, 0.00, NULL),
  ('2025-07-28', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-07-31', 'T5 Stores', 'Groceries', 1.90, FALSE, 0.00, NULL),
  ('2025-08-07', 'M AND S', 'Groceries', 1.75, FALSE, 0.00, NULL),
  ('2025-08-07', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-08-07', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-08-09', 'T5 Stores', 'Groceries', 2.98, FALSE, 0.00, NULL),
  ('2025-08-13', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-08-14', 'Tesco', 'Groceries', 23.95, FALSE, 0.00, NULL),
  ('2025-08-19', 'Tesco', 'Groceries', 8.45, FALSE, 0.00, NULL),
  ('2025-08-20', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-08-22', 'Nikki Karaoke', 'Host', 125.00, FALSE, 0.00, NULL),
  ('2025-08-23', 'Jermaine Flip Beats', 'dj deposit for halloween and new yr eve', 100.00, FALSE, 0.00, NULL),
  ('2025-08-25', 'Tesco', 'Groceries', 24.37, FALSE, 0.00, NULL),
  ('2025-08-25', 'Tesco', 'Groceries', 12.00, FALSE, 0.00, NULL),
  ('2025-08-28', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-08-28', 'Dan', 'weeding fix fence', 135.00, FALSE, 0.00, NULL),
  ('2025-08-29', 'Cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-09-01', 'Mr Fizz', 'Gas', 65.50, TRUE, 10.92, NULL),
  ('2025-09-01', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-09-02', 'Tesco', 'Groceries', 14.46, FALSE, 0.00, NULL),
  ('2025-09-03', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-09-04', 'M AND S', 'Groceries', 2.50, FALSE, 0.00, NULL),
  ('2025-09-04', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-09-05', 'T5 Stores', 'Groceries', 6.18, FALSE, 0.00, NULL),
  ('2025-09-08', 'Tesco', 'Groceries', 10.02, FALSE, 0.00, NULL),
  ('2025-09-10', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-09-11', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-09-13', 'New Bettola', 'meal out meeting', 130.33, FALSE, 0.00, NULL),
  ('2025-09-16', 'Tesco', 'Groceries', 3.78, FALSE, 0.00, NULL),
  ('2025-09-17', 'M AND S', 'Groceries', 2.50, FALSE, 0.00, NULL),
  ('2025-09-17', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-09-18', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-09-19', 'Tesco', 'Groceries', 10.14, FALSE, 0.00, NULL),
  ('2025-09-19', 'Cash Bingo', 'host', 50.00, FALSE, 0.00, NULL),
  ('2025-09-21', 'Tesco', 'stock take  and Groceries', 35.04, FALSE, 0.00, NULL),
  ('2025-09-24', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-09-24', 'Nikki Game Show', 'host', 125.00, FALSE, 0.00, NULL),
  ('2025-09-25', 'Tesco', 'Groceries', 3.68, FALSE, 0.00, NULL),
  ('2025-09-29', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2025-09-30', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2025-10-01', 'Tesco', 'Groceries', 11.16, FALSE, 0.00, NULL),
  ('2025-10-01', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-10-02', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-10-05', 'T5 Store', 'Groceries', 3.00, FALSE, 0.00, NULL),
  ('2025-10-05', 'T5 Store', 'Groceries', 7.50, FALSE, 0.00, NULL),
  ('2025-10-05', 'Dan', 'Gardening', 100.00, FALSE, 0.00, NULL),
  ('2025-10-07', 'Tesco', 'Groceries', 10.75, FALSE, 0.00, NULL),
  ('2025-10-08', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-10-15', 'Tesco', 'Groceries', 9.77, FALSE, 0.00, NULL),
  ('2025-10-16', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-10-16', 'Tesco', 'Groceries', 23.29, FALSE, 0.00, NULL),
  ('2025-10-16', 'T K Maxx', 'halloween dec', 26.98, FALSE, 0.00, NULL),
  ('2025-10-17', 'Tesco', 'Groceries', 20.85, FALSE, 0.00, NULL),
  ('2025-10-17', 'The Anchor', 'Lance Halloween dec pub', 100.00, FALSE, 0.00, NULL),
  ('2025-10-17', 'Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-10-21', 'T5 Store', 'Groceries', 1.79, FALSE, 0.00, NULL),
  ('2025-10-22', 'H and M', 'costume', 9.19, FALSE, 0.00, NULL),
  ('2025-10-24', 'T5 Store', 'Groceries', 3.75, FALSE, 0.00, NULL),
  ('2025-10-25', 'Tesco', 'Groceries', 13.46, FALSE, 0.00, NULL),
  ('2025-10-27', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2025-10-28', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-10-28', 'T5 Store', 'Groceries', 1.29, FALSE, 0.00, NULL),
  ('2025-10-29', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-10-29', 'M and S', 'Groceries', 2.45, FALSE, 0.00, NULL),
  ('2025-10-31', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-11-01', 'T5 Stores', 'Groceries', 3.79, FALSE, 0.00, NULL),
  ('2025-11-03', 'Tesco', 'Groceries', 9.26, FALSE, 0.00, NULL),
  ('2025-11-04', 'Tesco', 'Groceries', 30.17, FALSE, 0.00, NULL),
  ('2025-11-05', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-11-05', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-11-07', 'Tasting Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-11-11', 'Tesco', 'Groceries', 3.78, FALSE, 0.00, NULL),
  ('2025-11-12', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-11-13', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-11-13', 'Tesco', 'Groceries', 17.66, FALSE, 0.00, NULL),
  ('2025-11-14', 'Cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-11-15', 'Tesco', 'Groceries', 33.01, FALSE, 0.00, NULL),
  ('2025-11-29', 'T5 Stores', 'Groceries', 3.80, FALSE, 0.00, NULL),
  ('2025-11-30', 'T5 Stores', 'Groceries', 2.75, FALSE, 0.00, NULL),
  ('2025-12-02', 'Amazon', 'Decorations', 9.99, TRUE, 1.67, NULL),
  ('2025-12-02', 'Amazon', 'Decorations', 12.99, TRUE, 2.17, NULL),
  ('2025-12-03', 'Tesco', 'Groceries', 3.50, FALSE, 0.00, NULL),
  ('2025-12-13', 'Tesco', 'Groceries', 10.56, FALSE, 0.00, NULL),
  ('2025-12-05', 'Tesco', 'Groceries', 5.89, FALSE, 0.00, NULL),
  ('2025-12-10', 'Tesco', 'Groceries', 6.89, FALSE, 0.00, NULL),
  ('2025-12-28', 'Tesco', 'Groceries', 9.25, FALSE, 0.00, NULL),
  ('2025-12-22', 'Tesco', 'Groceries', 15.53, FALSE, 0.00, NULL),
  ('2025-12-06', 'Tesco', 'Groceries', 6.28, FALSE, 0.00, NULL),
  ('2025-12-24', 'Tesco', 'Groceries', 10.35, FALSE, 0.00, NULL),
  ('2025-12-19', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-12-04', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-12-30', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-12-08', 'Two Rivers Car Park', 'Parking', 2.70, FALSE, 0.00, NULL),
  ('2025-12-10', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2025-12-01', 'New bench', 'Bench was broken', 200.00, FALSE, 0.00, NULL),
  ('2025-12-03', 'Nikki Game Show', 'Host', 125.00, FALSE, 0.00, NULL),
  ('2025-12-11', 'Nikki Game Show DHL', 'Host for DHL', 175.00, FALSE, 0.00, NULL),
  ('2025-12-10', 'Quiz Night', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-12-20', 'Martin', 'Kitchen hand temp help', 174.00, FALSE, 0.00, NULL),
  ('2025-12-19', 'Cash Bingo', 'Host', 50.00, FALSE, 0.00, NULL),
  ('2025-12-21', 'Browns', 'working dinner', 249.90, FALSE, 0.00, NULL);

-- =============================================================
-- MGD Returns (historical import)
-- =============================================================
-- Insert returns FIRST, then disable the collection trigger,
-- insert collections, recalculate totals, then re-enable trigger.

-- Disable the auto-sync trigger during bulk import
ALTER TABLE public.mgd_collections DISABLE TRIGGER trg_mgd_collection_sync;

INSERT INTO public.mgd_returns (period_start, period_end, total_net_take, total_mgd, total_vat_on_supplier, status, date_paid) VALUES
  ('2019-02-01', '2019-04-30', 339.00, 67.00, 0, 'submitted', NULL),
  ('2019-05-01', '2019-07-31', 409.00, 81.00, 0, 'submitted', NULL),
  ('2019-08-01', '2019-10-31', 976.00, 195.00, 0, 'submitted', NULL),
  ('2019-11-01', '2020-01-31', 3189.00, 637.00, 0, 'submitted', NULL),
  ('2020-02-01', '2020-04-30', 2008.00, 401.00, 0, 'submitted', NULL),
  ('2020-05-01', '2020-07-31', 929.00, 184.00, 0, 'submitted', NULL),
  ('2020-08-01', '2020-10-31', 3152.00, 630.00, 0, 'submitted', NULL),
  ('2020-11-01', '2021-01-31', 495.00, 99.00, 0, 'submitted', NULL),
  ('2021-02-01', '2021-04-30', 0.00, 0.00, 0, 'submitted', NULL),
  ('2021-05-01', '2021-07-31', 1810.00, 360.00, 0, 'submitted', NULL),
  ('2021-08-01', '2021-10-31', 2107.00, 421.00, 0, 'submitted', NULL),
  ('2021-11-01', '2022-01-31', 757.00, 257.00, 0, 'submitted', NULL),
  ('2022-02-01', '2022-04-30', 4384.00, 876.00, 0, 'submitted', NULL),
  ('2022-05-01', '2022-07-31', 5122.00, 1024.00, 0, 'submitted', NULL),
  ('2022-08-01', '2022-10-31', 1841.00, 368.00, 0, 'submitted', NULL),
  ('2022-11-01', '2023-01-31', 4893.00, 978.00, 0, 'submitted', NULL),
  ('2023-02-01', '2023-04-30', 1978.00, 395.00, 0, 'submitted', NULL),
  ('2023-05-01', '2023-07-31', 3558.00, 711.00, 0, 'submitted', NULL),
  ('2023-08-01', '2023-10-31', 4154.00, 830.00, 0, 'submitted', NULL),
  ('2023-11-01', '2024-01-31', 6799.00, 1359.00, 0, 'submitted', NULL),
  ('2024-02-01', '2024-04-30', 3754.00, 750.00, 0, 'paid', '2024-06-30'),
  ('2024-05-01', '2024-07-31', 4317.00, 862.00, 0, 'paid', '2024-10-01'),
  ('2024-08-01', '2024-10-31', 4460.00, 892.00, 0, 'paid', '2025-02-07'),
  ('2024-11-01', '2025-01-31', 2673.00, 536.00, 0, 'paid', '2025-02-07'),
  ('2025-02-01', '2025-04-30', 2715.00, 543.00, 0, 'paid', '2025-06-30'),
  ('2025-05-01', '2025-07-31', 2755.00, 551.00, 0, 'paid', '2025-10-31'),
  ('2025-08-01', '2025-10-31', 5107.00, 1021.00, 0, 'paid', '2026-01-23'),
  ('2025-11-01', '2026-01-31', 4016.00, 803.00, 0, 'submitted', NULL),
  ('2026-02-01', '2026-04-30', 588.00, 117.00, 0, 'open', NULL),
  ('2026-05-01', '2026-07-31', 0.00, 0.00, 0, 'open', NULL),
  ('2026-08-01', '2026-10-31', 0.00, 0.00, 0, 'open', NULL),
  ('2026-11-01', '2027-01-31', 0.00, 0.00, 0, 'open', NULL);

-- =============================================================
-- MGD Collections (historical import)
-- =============================================================

INSERT INTO public.mgd_collections (collection_date, net_take, vat_on_supplier, created_by) VALUES
  ('2026-02-25', 588.75, 7.59, NULL),
  ('2026-01-28', 164.00, 7.59, NULL),
  ('2025-12-31', 462.70, 16.90, NULL),
  ('2025-12-24', 1138.05, 50.69, NULL),
  ('2025-12-03', 2251.90, 101.39, NULL),
  ('2025-10-22', 2733.55, 67.59, NULL),
  ('2025-09-24', 836.65, 33.80, NULL),
  ('2025-09-10', 1414.60, 67.59, NULL),
  ('2025-08-13', 122.30, 50.69, NULL),
  ('2025-07-23', 392.05, 50.69, NULL),
  ('2025-07-02', 1075.50, 67.59, NULL),
  ('2025-06-04', 1041.70, 67.59, NULL),
  ('2025-05-07', 246.50, 16.90, NULL),
  ('2025-04-30', 1365.60, 84.49, NULL),
  ('2025-03-26', 221.00, 33.80, NULL),
  ('2025-03-12', 55.20, 33.80, NULL),
  ('2025-02-26', 17.50, 14.48, NULL),
  ('2025-02-20', 1056.45, 50.69, NULL),
  ('2025-01-30', 507.65, 38.62, NULL),
  ('2025-01-14', 730.70, 65.18, NULL),
  ('2024-12-18', 585.45, 50.69, NULL),
  ('2024-11-27', 362.80, 50.69, NULL),
  ('2024-11-06', 486.70, 33.80, NULL),
  ('2024-10-23', 2143.00, 67.59, NULL),
  ('2024-09-25', 304.70, 33.80, NULL),
  ('2024-09-11', 257.50, 33.80, NULL),
  ('2024-08-28', 840.30, 33.80, NULL),
  ('2024-08-14', 915.10, 33.80, NULL),
  ('2024-07-31', 842.80, 33.80, NULL),
  ('2024-07-17', 715.40, 33.80, NULL),
  ('2024-07-03', 358.35, 33.80, NULL),
  ('2024-06-19', 272.15, 19.31, NULL),
  ('2024-06-11', 1132.90, 48.28, NULL),
  ('2024-05-22', 241.15, 33.80, NULL),
  ('2024-05-08', 754.60, 33.80, NULL),
  ('2024-04-24', 611.75, 33.80, NULL),
  ('2024-04-10', 252.65, 33.80, NULL),
  ('2024-03-27', 616.30, 36.21, NULL),
  ('2024-03-12', 1559.30, 65.18, NULL),
  ('2024-02-14', 714.25, 33.80, NULL),
  ('2024-01-31', 535.65, 20.00, NULL),
  ('2024-01-17', 1119.60, 28.57, NULL),
  ('2023-12-28', 1208.30, 22.86, NULL),
  ('2023-12-12', 1118.90, 20.00, NULL),
  ('2023-11-28', 830.60, 17.14, NULL),
  ('2023-11-16', 676.70, 17.14, NULL),
  ('2023-11-02', 1310.00, 20.00, NULL),
  ('2023-10-19', 861.45, 20.00, NULL),
  ('2023-10-05', 1124.65, 20.00, NULL),
  ('2023-09-21', 2168.15, 14.29, NULL),
  ('2023-07-18', 1100.95, 20.00, NULL),
  ('2023-07-04', 463.00, 28.57, NULL),
  ('2023-06-14', 1174.15, 40.00, NULL),
  ('2023-05-17', 820.25, 40.00, NULL),
  ('2023-04-19', 416.05, 31.43, NULL),
  ('2023-03-28', 605.90, 40.00, NULL),
  ('2023-02-28', 956.30, 48.57, NULL),
  ('2023-01-25', 1361.35, 40.00, NULL),
  ('2022-12-28', 993.75, 38.57, NULL),
  ('2022-12-01', 1268.80, 41.43, NULL),
  ('2022-11-02', 1270.00, 40.00, NULL),
  ('2022-10-05', 1256.35, 40.00, NULL),
  ('2022-09-07', 234.45, 40.00, NULL),
  ('2022-08-10', 350.20, 20.00, NULL),
  ('2022-07-29', 1323.65, 40.00, NULL),
  ('2022-07-27', 1246.20, 40.00, NULL),
  ('2022-06-01', 1209.05, 40.00, NULL),
  ('2022-05-04', 1343.60, 38.57, NULL),
  ('2022-04-07', 1256.25, 41.43, NULL),
  ('2022-03-09', 1789.65, 40.00, NULL),
  ('2022-02-09', 1338.20, 81.43, NULL),
  ('2021-12-14', 515.00, 38.57, NULL),
  ('2021-11-30', 183.70, 14.70, NULL),
  ('2021-11-17', 58.50, 40.00, NULL),
  ('2021-10-20', 626.15, 40.00, NULL),
  ('2021-09-22', 580.85, 40.00, NULL),
  ('2021-08-25', 433.90, 28.57, NULL),
  ('2021-08-25', 466.20, 11.43, NULL),
  ('2021-07-28', 533.25, 30.00, NULL),
  ('2021-07-07', 1276.80, 72.86, NULL),
  ('2020-11-04', 495.30, 8.57, NULL),
  ('2020-10-29', 805.10, 20.00, NULL),
  ('2020-10-15', 177.70, 20.00, NULL),
  ('2020-10-01', 233.30, 20.00, NULL),
  ('2020-09-17', 414.80, 20.00, NULL),
  ('2020-09-03', 144.60, 20.00, NULL),
  ('2020-08-20', 1376.50, 40.00, NULL),
  ('2020-07-23', 731.70, 27.14, NULL),
  ('2020-07-02', 197.75, 14.29, NULL),
  ('2020-03-11', 171.45, 18.57, NULL),
  ('2020-02-27', 1158.75, 30.00, NULL),
  ('2020-02-06', 678.30, 20.00, NULL),
  ('2020-01-23', 773.35, 20.00, NULL),
  ('2020-01-09', 963.65, 77.09, NULL),
  ('2019-12-27', 686.10, 54.89, NULL),
  ('2019-12-11', 183.30, 14.66, NULL),
  ('2019-11-28', 220.80, 17.66, NULL),
  ('2019-11-01', 362.05, 28.96, NULL),
  ('2019-10-17', 109.10, 8.73, NULL),
  ('2019-10-03', 253.00, 20.24, NULL),
  ('2019-09-19', 66.55, 4.32, NULL),
  ('2019-09-05', 326.80, 14.00, NULL),
  ('2019-09-05', 90.30, 7.22, NULL),
  ('2019-08-22', 130.50, 28.00, NULL),
  ('2019-07-25', 68.75, 28.00, NULL),
  ('2019-06-27', 208.75, 28.00, NULL),
  ('2019-05-30', 0.00, 9.00, NULL),
  ('2019-05-21', 6.00, 5.00, NULL),
  ('2019-05-16', 125.50, 28.00, NULL),
  ('2019-04-18', 79.25, 9.00, NULL),
  ('2019-04-04', 56.00, 14.00, NULL),
  ('2019-03-21', 204.40, 16.00, NULL);

-- Recalculate return totals from actual collection data
UPDATE public.mgd_returns r SET
  total_net_take = COALESCE(sub.sum_net, 0),
  total_mgd = COALESCE(sub.sum_mgd, 0),
  total_vat_on_supplier = COALESCE(sub.sum_vat, 0)
FROM (
  SELECT
    ret.id,
    SUM(c.net_take) AS sum_net,
    SUM(c.mgd_amount) AS sum_mgd,
    SUM(c.vat_on_supplier) AS sum_vat
  FROM public.mgd_returns ret
  LEFT JOIN public.mgd_collections c
    ON c.collection_date >= ret.period_start
    AND c.collection_date <= ret.period_end
  GROUP BY ret.id
) sub
WHERE r.id = sub.id;

-- Re-enable the auto-sync trigger
ALTER TABLE public.mgd_collections ENABLE TRIGGER trg_mgd_collection_sync;
