-- Customer consent audit and permission hardening.
-- Additive migration: creates the consent audit trail, missing summary fields,
-- transactional writer RPC, RBAC grants, and legacy evidence report view.

SET search_path = public, extensions;

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS sms_opt_in_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sms_opted_out_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_sms_opt_in_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_sms_opted_out_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_email_opt_in_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_email_opted_out_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_whatsapp_opt_in_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_whatsapp_opted_out_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sms_opt_in_source TEXT,
  ADD COLUMN IF NOT EXISTS whatsapp_opt_in_source TEXT;

CREATE TABLE IF NOT EXISTS public.customer_consents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  purpose TEXT NOT NULL,
  status TEXT NOT NULL,
  legal_basis TEXT NOT NULL,
  source TEXT NOT NULL,
  capture_method TEXT NOT NULL,
  consent_text_version TEXT,
  consent_text TEXT,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  captured_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  source_url TEXT,
  ip_hash TEXT,
  user_agent TEXT,
  related_entity_type TEXT,
  related_entity_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT customer_consents_channel_check
    CHECK (channel IN ('email', 'sms', 'whatsapp')),
  CONSTRAINT customer_consents_purpose_check
    CHECK (purpose IN ('service', 'marketing')),
  CONSTRAINT customer_consents_status_check
    CHECK (status IN ('opted_in', 'opted_out', 'objected', 'unknown', 'legacy')),
  CONSTRAINT customer_consents_legal_basis_check
    CHECK (legal_basis IN ('contract', 'legitimate_interests', 'consent', 'soft_opt_in', 'unknown')),
  CONSTRAINT customer_consents_source_check
    CHECK (source IN (
      'public_table_booking',
      'public_event_booking',
      'public_event_waitlist',
      'public_private_booking',
      'public_parking_booking',
      'staff_table_booking',
      'staff_event_booking',
      'staff_private_booking',
      'staff_parking_booking',
      'customer_profile',
      'customer_import',
      'customer_lookup_legacy',
      'twilio_inbound_sms',
      'twilio_inbound_whatsapp',
      'direct_message',
      'system_migration',
      'gdpr_action'
    )),
  CONSTRAINT customer_consents_capture_method_check
    CHECK (capture_method IN (
      'checkbox',
      'staff_verbal',
      'profile_toggle',
      'import_attestation',
      'api_field',
      'inbound_keyword',
      'system_migration',
      'service_notice',
      'provider_event'
    )),
  CONSTRAINT customer_consents_related_entity_type_check
    CHECK (
      related_entity_type IS NULL OR related_entity_type IN (
        'table_booking',
        'event_booking',
        'event_waitlist',
        'private_booking',
        'parking_booking',
        'customer',
        'message',
        'import'
      )
    )
);

CREATE INDEX IF NOT EXISTS idx_customer_consents_customer_latest
  ON public.customer_consents (customer_id, captured_at DESC, event_sequence DESC);

CREATE INDEX IF NOT EXISTS idx_customer_consents_channel_status
  ON public.customer_consents (channel, purpose, status, captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_customer_consents_related_entity
  ON public.customer_consents (related_entity_type, related_entity_id)
  WHERE related_entity_type IS NOT NULL AND related_entity_id IS NOT NULL;

DROP TRIGGER IF EXISTS update_customer_consents_updated_at ON public.customer_consents;
CREATE TRIGGER update_customer_consents_updated_at
  BEFORE UPDATE ON public.customer_consents
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.customer_consents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages customer consents" ON public.customer_consents;
CREATE POLICY "Service role manages customer consents"
  ON public.customer_consents
  FOR ALL TO service_role
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Authenticated users view customer consent summaries" ON public.customer_consents;
CREATE POLICY "Authenticated users view customer consent summaries"
  ON public.customer_consents
  FOR SELECT TO authenticated
  USING (
    public.user_has_permission(auth.uid(), 'customers', 'view_contact_preferences')
    OR public.user_has_permission(auth.uid(), 'messages', 'view_consent_audit')
  );

REVOKE ALL ON public.customer_consents FROM anon, authenticated;
GRANT SELECT ON public.customer_consents TO authenticated;
GRANT ALL ON public.customer_consents TO service_role;

CREATE OR REPLACE FUNCTION public.record_customer_consent(
  p_customer_id UUID,
  p_channel TEXT,
  p_purpose TEXT,
  p_status TEXT,
  p_legal_basis TEXT,
  p_source TEXT,
  p_capture_method TEXT,
  p_consent_text_version TEXT DEFAULT NULL,
  p_consent_text TEXT DEFAULT NULL,
  p_captured_by_user_id UUID DEFAULT NULL,
  p_source_url TEXT DEFAULT NULL,
  p_ip_hash TEXT DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL,
  p_related_entity_type TEXT DEFAULT NULL,
  p_related_entity_id TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb,
  p_update_summary BOOLEAN DEFAULT TRUE
) RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_consent_id UUID;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  PERFORM 1 FROM public.customers WHERE id = p_customer_id FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Customer % not found', p_customer_id USING ERRCODE = 'P0002';
  END IF;

  INSERT INTO public.customer_consents (
    customer_id,
    channel,
    purpose,
    status,
    legal_basis,
    source,
    capture_method,
    consent_text_version,
    consent_text,
    captured_at,
    captured_by_user_id,
    source_url,
    ip_hash,
    user_agent,
    related_entity_type,
    related_entity_id,
    metadata
  ) VALUES (
    p_customer_id,
    p_channel,
    p_purpose,
    p_status,
    p_legal_basis,
    p_source,
    p_capture_method,
    p_consent_text_version,
    p_consent_text,
    v_now,
    p_captured_by_user_id,
    p_source_url,
    p_ip_hash,
    p_user_agent,
    p_related_entity_type,
    p_related_entity_id,
    COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_consent_id;

  IF p_update_summary IS TRUE THEN
    IF p_channel = 'sms' AND p_purpose = 'service' THEN
      IF p_status = 'opted_in' THEN
        UPDATE public.customers
        SET sms_opt_in = TRUE,
            sms_status = 'active',
            sms_opt_in_at = v_now,
            sms_opt_in_source = p_source,
            sms_delivery_failures = 0,
            sms_deactivated_at = NULL,
            sms_deactivation_reason = NULL
        WHERE id = p_customer_id;
      ELSIF p_status IN ('opted_out', 'objected') THEN
        UPDATE public.customers
        SET sms_opt_in = FALSE,
            sms_status = 'opted_out',
            sms_opted_out_at = v_now,
            marketing_sms_opt_in = FALSE,
            marketing_sms_opted_out_at = v_now,
            sms_deactivated_at = NULL,
            sms_deactivation_reason = NULL
        WHERE id = p_customer_id;
      END IF;
    ELSIF p_channel = 'sms' AND p_purpose = 'marketing' THEN
      IF p_status = 'opted_in' THEN
        UPDATE public.customers
        SET marketing_sms_opt_in = TRUE,
            marketing_sms_opt_in_at = v_now
        WHERE id = p_customer_id;
      ELSIF p_status IN ('opted_out', 'objected') THEN
        UPDATE public.customers
        SET marketing_sms_opt_in = FALSE,
            marketing_sms_opted_out_at = v_now
        WHERE id = p_customer_id;
      END IF;
    ELSIF p_channel = 'email' AND p_purpose = 'marketing' THEN
      IF p_status = 'opted_in' THEN
        UPDATE public.customers
        SET marketing_email_opt_in = TRUE,
            marketing_email_opt_in_at = v_now
        WHERE id = p_customer_id;
      ELSIF p_status IN ('opted_out', 'objected') THEN
        UPDATE public.customers
        SET marketing_email_opt_in = FALSE,
            marketing_email_opted_out_at = v_now
        WHERE id = p_customer_id;
      END IF;
    ELSIF p_channel = 'whatsapp' AND p_purpose = 'service' THEN
      IF p_status = 'opted_in' THEN
        UPDATE public.customers
        SET whatsapp_opt_in = TRUE,
            whatsapp_status = 'active',
            whatsapp_opt_in_at = v_now,
            whatsapp_opted_out_at = NULL,
            whatsapp_opt_in_source = p_source,
            whatsapp_delivery_failures = 0,
            last_whatsapp_failure_reason = NULL,
            whatsapp_deactivated_at = NULL,
            whatsapp_deactivation_reason = NULL
        WHERE id = p_customer_id;
      ELSIF p_status IN ('opted_out', 'objected') THEN
        UPDATE public.customers
        SET whatsapp_opt_in = FALSE,
            whatsapp_status = 'opted_out',
            whatsapp_opted_out_at = v_now,
            marketing_whatsapp_opt_in = FALSE,
            marketing_whatsapp_opted_out_at = v_now,
            whatsapp_deactivated_at = NULL,
            whatsapp_deactivation_reason = NULL
        WHERE id = p_customer_id;
      END IF;
    ELSIF p_channel = 'whatsapp' AND p_purpose = 'marketing' THEN
      IF p_status = 'opted_in' THEN
        UPDATE public.customers
        SET marketing_whatsapp_opt_in = TRUE,
            marketing_whatsapp_opt_in_at = v_now
        WHERE id = p_customer_id;
      ELSIF p_status IN ('opted_out', 'objected') THEN
        UPDATE public.customers
        SET marketing_whatsapp_opt_in = FALSE,
            marketing_whatsapp_opted_out_at = v_now
        WHERE id = p_customer_id;
      END IF;
    END IF;
  END IF;

  RETURN v_consent_id;
END;
$$;

REVOKE ALL ON FUNCTION public.record_customer_consent(
  UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, BOOLEAN
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.record_customer_consent(
  UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, BOOLEAN
) TO service_role;

INSERT INTO public.permissions (module_name, action, description)
VALUES
  ('customers', 'view_contact_preferences', 'View customer contact preference state'),
  ('customers', 'manage_contact_preferences', 'Manage customer contact preferences'),
  ('customers', 'manage_whatsapp_opt_in', 'Manage customer WhatsApp opt-in'),
  ('customers', 'record_service_contact', 'Record service-contact notice during staff booking flows'),
  ('messages', 'send_transactional', 'Send transactional customer communications'),
  ('messages', 'send_marketing', 'Send marketing customer communications'),
  ('messages', 'view_consent_audit', 'View customer consent audit trail'),
  ('messages', 'export_consent_audit', 'Export customer consent audit evidence')
ON CONFLICT (module_name, action) DO UPDATE
SET description = EXCLUDED.description;

INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.name = 'super_admin'
  AND (
    (p.module_name = 'customers' AND p.action IN (
      'view_contact_preferences',
      'manage_contact_preferences',
      'manage_whatsapp_opt_in',
      'record_service_contact'
    ))
    OR (p.module_name = 'messages' AND p.action IN (
      'send_transactional',
      'send_marketing',
      'view_consent_audit',
      'export_consent_audit'
    ))
  )
ON CONFLICT DO NOTHING;

INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.name = 'manager'
  AND (
    (p.module_name = 'customers' AND p.action IN (
      'view_contact_preferences',
      'manage_contact_preferences',
      'manage_whatsapp_opt_in',
      'record_service_contact'
    ))
    OR (p.module_name = 'messages' AND p.action IN (
      'send_transactional',
      'send_marketing',
      'view_consent_audit'
    ))
  )
ON CONFLICT DO NOTHING;

INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.name = 'staff'
  AND (
    (p.module_name = 'customers' AND p.action IN (
      'view_contact_preferences',
      'record_service_contact'
    ))
    OR (p.module_name = 'messages' AND p.action = 'send_transactional')
  )
ON CONFLICT DO NOTHING;

INSERT INTO public.customer_consents (
  customer_id,
  channel,
  purpose,
  status,
  legal_basis,
  source,
  capture_method,
  consent_text_version,
  consent_text,
  metadata
)
SELECT c.id, legacy.channel, legacy.purpose, 'legacy', 'unknown', 'system_migration',
       'system_migration', 'legacy-system-state', NULL,
       jsonb_build_object('summary_field', legacy.summary_field, 'summary_value', true)
FROM public.customers c
CROSS JOIN LATERAL (
  VALUES
    ('sms', 'service', 'sms_opt_in', COALESCE(c.sms_opt_in, false)),
    ('sms', 'marketing', 'marketing_sms_opt_in', COALESCE(c.marketing_sms_opt_in, false)),
    ('email', 'marketing', 'marketing_email_opt_in', COALESCE(c.marketing_email_opt_in, false)),
    ('whatsapp', 'service', 'whatsapp_opt_in', COALESCE(c.whatsapp_opt_in, false)),
    ('whatsapp', 'marketing', 'marketing_whatsapp_opt_in', COALESCE(c.marketing_whatsapp_opt_in, false))
) AS legacy(channel, purpose, summary_field, is_enabled)
WHERE legacy.is_enabled = true
  AND NOT EXISTS (
    SELECT 1
    FROM public.customer_consents cc
    WHERE cc.customer_id = c.id
      AND cc.channel = legacy.channel
      AND cc.purpose = legacy.purpose
      AND cc.source = 'system_migration'
      AND cc.capture_method = 'system_migration'
      AND cc.status = 'legacy'
      AND cc.metadata->>'summary_field' = legacy.summary_field
  );

CREATE OR REPLACE VIEW public.customer_consent_legacy_gaps AS
SELECT
  c.id AS customer_id,
  c.first_name,
  c.last_name,
  c.mobile_number,
  c.email,
  field.summary_field,
  field.channel,
  field.purpose,
  field.summary_value
FROM public.customers c
CROSS JOIN LATERAL (
  VALUES
    ('sms_opt_in', 'sms', 'service', COALESCE(c.sms_opt_in, false)),
    ('marketing_sms_opt_in', 'sms', 'marketing', COALESCE(c.marketing_sms_opt_in, false)),
    ('marketing_email_opt_in', 'email', 'marketing', COALESCE(c.marketing_email_opt_in, false)),
    ('whatsapp_opt_in', 'whatsapp', 'service', COALESCE(c.whatsapp_opt_in, false)),
    ('marketing_whatsapp_opt_in', 'whatsapp', 'marketing', COALESCE(c.marketing_whatsapp_opt_in, false))
) AS field(summary_field, channel, purpose, summary_value)
WHERE field.summary_value = true
  AND NOT EXISTS (
    SELECT 1
    FROM public.customer_consents cc
    WHERE cc.customer_id = c.id
      AND cc.channel = field.channel
      AND cc.purpose = field.purpose
  );

GRANT SELECT ON public.customer_consent_legacy_gaps TO authenticated, service_role;
