-- =============================================================
-- Migration: Import Historical 2024 Data from Excel Spreadsheets
-- Generated by: scripts/import-historical-data-2024.py
-- Generated at: 2026-04-05T11:27:49.126580
-- =============================================================
-- Data sources:
--   1. Mileage Tracker - 2024.xlsx (Jan-Feb, 37 trips)
--   2. Petty Cash - 2024.xlsx (Jan-Dec, 335 expenses)
-- =============================================================

-- =============================================================
-- Mileage Trips (historical import: Jan-Feb 2024)
-- =============================================================

-- Insert any destinations not already seeded
INSERT INTO public.mileage_destinations (name) SELECT 'Bookers' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Bookers');
INSERT INTO public.mileage_destinations (name) SELECT 'Costco' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Costco');
INSERT INTO public.mileage_destinations (name) SELECT 'Ikea reading' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Ikea reading');
INSERT INTO public.mileage_destinations (name) SELECT 'Tesco - Ashford' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Tesco - Ashford');
INSERT INTO public.mileage_destinations (name) SELECT 'Two Rivers Car Park' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park');
INSERT INTO public.mileage_destinations (name) SELECT 'Windsor Cr Park' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'Windsor Cr Park');
INSERT INTO public.mileage_destinations (name) SELECT 'mexicanos staines' WHERE NOT EXISTS (SELECT 1 FROM public.mileage_destinations WHERE name = 'mexicanos staines');

-- Insert trips and their legs
DO $$
DECLARE
  v_trip_id UUID;
  v_anchor_id UUID;
  v_dest_id UUID;
BEGIN
  -- Get the Anchor (home base) destination ID
  SELECT id INTO v_anchor_id FROM public.mileage_destinations WHERE is_home_base = TRUE LIMIT 1;

  -- Trip 1: 2024-01-01 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-01', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 2: 2024-01-02 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-02', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 3: 2024-01-02 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-02', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 4: 2024-01-16 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-16', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 5: 2024-01-20 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-20', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 6: 2024-01-20 -> Ikea reading (62.0 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Ikea reading' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-20', 'Ikea reading', 62.0, 62.0, 0, 27.90, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 31.0);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 31.0);

  -- Trip 7: 2024-01-20 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-20', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 8: 2024-01-29 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-29', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 9: 2024-01-23 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-23', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 10: 2024-01-29 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-29', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 11: 2024-01-30 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-30', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 12: 2024-01-30 -> Windsor Cr Park (17.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Windsor Cr Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-01-30', 'Windsor Cr Park', 17.6, 17.6, 0, 7.92, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 8.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 8.8);

  -- Trip 13: 2024-02-01 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-01', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 14: 2024-02-01 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-01', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 15: 2024-02-01 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-01', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 16: 2024-02-02 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-02', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 17: 2024-02-03 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-03', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 18: 2024-02-04 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-04', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 19: 2024-02-06 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-06', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 20: 2024-02-07 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-07', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 21: 2024-02-08 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-08', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 22: 2024-02-09 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-09', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 23: 2024-02-10 -> Costco (2.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Costco' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-10', 'Costco', 2.4, 2.4, 0, 1.08, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.2);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.2);

  -- Trip 24: 2024-02-13 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-13', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 25: 2024-02-15 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-15', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 26: 2024-02-16 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-16', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 27: 2024-02-17 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-17', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 28: 2024-02-18 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-18', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 29: 2024-02-20 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-20', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 30: 2024-02-21 -> Two Rivers Car Park (7.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Two Rivers Car Park' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-21', 'Two Rivers Car Park', 7.4, 7.4, 0, 3.33, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.7);

  -- Trip 31: 2024-02-22 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-22', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

  -- Trip 32: 2024-02-23 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-23', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 33: 2024-02-24 -> mexicanos staines (6.0 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'mexicanos staines' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-24', 'mexicanos staines', 6.0, 6.0, 0, 2.70, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 3.0);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 3.0);

  -- Trip 34: 2024-02-26 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-26', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 35: 2024-02-27 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-27', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 36: 2024-02-29 -> Tesco - Ashford (3.4 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Tesco - Ashford' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-29', 'Tesco - Ashford', 3.4, 3.4, 0, 1.53, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 1.7);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 1.7);

  -- Trip 37: 2024-02-28 -> Bookers (13.6 miles return)
  SELECT id INTO v_dest_id FROM public.mileage_destinations WHERE name = 'Bookers' LIMIT 1;
  INSERT INTO public.mileage_trips (trip_date, description, total_miles, miles_at_standard_rate, miles_at_reduced_rate, amount_due, source, created_by)
  VALUES ('2024-02-28', 'Bookers', 13.6, 13.6, 0, 6.12, 'manual', NULL)
  RETURNING id INTO v_trip_id;

  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 1, v_anchor_id, v_dest_id, 6.8);
  INSERT INTO public.mileage_trip_legs (trip_id, leg_order, from_destination_id, to_destination_id, miles)
  VALUES (v_trip_id, 2, v_dest_id, v_anchor_id, 6.8);

END;
$$;

-- =============================================================
-- Expenses (historical import: Jan-Dec 2024)
-- =============================================================

INSERT INTO public.expenses (expense_date, company_ref, justification, amount, vat_applicable, vat_amount, created_by) VALUES
  ('2024-01-02', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-01-02', 'M and S', 'Groceries', 8.30, FALSE, 0.00, NULL),
  ('2024-01-16', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-01-22', 'Mr Fizz', 'Gas', 63.00, TRUE, 12.60, NULL),
  ('2024-01-20', 'Tesco', 'Groceries', 5.88, FALSE, 0.00, NULL),
  ('2024-01-29', 'Tesco', 'Groceries', 7.72, FALSE, 0.00, NULL),
  ('2024-01-20', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-01-23', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-01-29', 'Rebecca Gibbons', 'Bar Cover', 60.00, FALSE, 0.00, NULL),
  ('2024-01-30', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-01-30', 'Windsor Car Park', 'Parking', 5.00, TRUE, 1.00, NULL),
  ('2024-01-30', 'Browns', 'Meal Meeting', 140.14, TRUE, 28.03, NULL),
  ('2024-02-02', 'Tesco', 'Groceries', 3.60, FALSE, 0.00, NULL),
  ('2024-02-12', 'Tesco', 'Groceries', 7.04, FALSE, 0.00, NULL),
  ('2023-02-07', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-02-06', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-02-15', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-02-17', 'Rebecca Gibbons', 'Bar Cover', 45.00, FALSE, 0.00, NULL),
  ('2024-02-18', 'Tesco', 'Groceries', 29.28, FALSE, 0.00, NULL),
  ('2024-02-06', 'M and S', 'Groceries', 1.45, FALSE, 0.00, NULL),
  ('2024-02-21', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-02-21', 'Poundland', 'Groceries', 3.75, FALSE, 0.00, NULL),
  ('2024-02-23', 'Tesco', 'Groceries', 1.33, FALSE, 0.00, NULL),
  ('2024-02-26', 'Tesco', 'Groceries', 1.45, FALSE, 0.00, NULL),
  ('2024-02-23', 'Tesco', 'Groceries', 8.03, FALSE, 0.00, NULL),
  ('2024-02-29', 'Tesco', 'Groceries', 19.23, FALSE, 0.00, NULL),
  ('2024-02-27', 'Tesco', 'Groceries', 4.08, FALSE, 0.00, NULL),
  ('2024-03-01', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-03-03', 'T5 Stores', 'Groceries', 3.59, FALSE, 0.00, NULL),
  ('2024-03-04', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-03-04', 'Poundland', 'Snacks', 9.00, FALSE, 0.00, NULL),
  ('2024-03-05', 'Tesco', 'Groceries', 43.04, FALSE, 0.00, NULL),
  ('2024-03-06', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-03-07', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-03-10', 'Sainsburys', 'Groceries', 2.20, FALSE, 0.00, NULL),
  ('2024-03-13', 'Tesco', 'Groceries', 8.71, FALSE, 0.00, NULL),
  ('2024-03-14', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-03-14', 'WHS', 'Parcel Tape', 1.49, FALSE, 0.00, NULL),
  ('2024-03-15', 'T5 Stores', 'Polish', 1.99, FALSE, 0.00, NULL),
  ('2024-03-15', 'Jasmin Januth', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-03-15', 'Tesco', 'bread', 0.75, FALSE, 0.00, NULL),
  ('2024-03-15', 'Tesco', 'Groceries', 7.27, FALSE, 0.00, NULL),
  ('2024-03-18', 'M and S', 'Groceries', 4.60, FALSE, 0.00, NULL),
  ('2024-03-18', 'Mr Fizz', 'Gas', 63.00, TRUE, 10.50, NULL),
  ('2024-03-21', 'Two Rivers Car Park', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-03-22', 'Jasmin Januth', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-03-24', 'T5 Stores', 'Groceries', 2.99, FALSE, 0.00, NULL),
  ('2024-03-24', 'T5 Stores', 'Groceries', 2.70, FALSE, 0.00, NULL),
  ('2024-03-28', 'Two Rivers Car Park', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-03-28', 'Tesco', 'Groceries', 22.75, FALSE, 0.00, NULL),
  ('2024-03-29', 'T5 Stores', 'Groceries', 3.00, FALSE, 0.00, NULL),
  ('2024-03-29', 'Yasmin Janvtih', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-04-01', 'Goddess Cleaners', 'Cleaning', 25.00, FALSE, 0.00, NULL),
  ('2024-04-02', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-04-02', 'Tesco', 'Groceries', 23.15, FALSE, 0.00, NULL),
  ('2024-04-03', 'Booker', 'Groceries', 94.82, TRUE, 2.40, NULL),
  ('2024-04-05', 'Booker', 'Groceries', 16.98, TRUE, 1.00, NULL),
  ('2024-04-11', 'T5 Stores', 'Groceries', 1.29, FALSE, 0.00, NULL),
  ('2024-04-11', 'Tesco', 'Groceries', 8.01, FALSE, 0.00, NULL),
  ('2024-04-12', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-04-12', 'Tesco', 'Groceries', 3.00, FALSE, 0.00, NULL),
  ('2024-04-13', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-04-13', 'Dan Brown', 'Gardening', 120.00, FALSE, 0.00, NULL),
  ('2024-04-15', 'Tesco', 'Groceries', 5.44, FALSE, 0.00, NULL),
  ('2024-04-15', 'MR Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2024-04-16', 'M and S', 'Groceries', 16.40, FALSE, 0.00, NULL),
  ('2024-04-16', 'Tesco', 'Groceries', 22.73, FALSE, 0.00, NULL),
  ('2024-04-17', 'T5 Stores', 'Groceries', 1.49, FALSE, 0.00, NULL),
  ('2024-04-19', 'T5 Stores', 'Groceries', 5.87, FALSE, 0.00, NULL),
  ('2024-04-19', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-04-20', 'Tesco', 'Groceries', 16.74, FALSE, 0.00, NULL),
  ('2024-04-22', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-04-23', 'M and S', 'Groceries', 9.45, FALSE, 0.00, NULL),
  ('2024-04-24', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-04-25', 'T5 Stores', 'Groceries', 5.83, FALSE, 0.00, NULL),
  ('2024-04-26', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-04-26', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-05-01', 'Poundland', 'Groceries', 8.25, FALSE, 0.00, NULL),
  ('2024-05-01', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-05-01', 'M and S', 'Groceries', 3.05, FALSE, 0.00, NULL),
  ('2024-05-02', 'Tesco', 'Groceries', 3.39, FALSE, 0.00, NULL),
  ('2024-05-03', 'T5 Stores', 'Groceries', 4.65, FALSE, 0.00, NULL),
  ('2024-05-03', 'T5 Stores', 'Groceries', 3.00, FALSE, 0.00, NULL),
  ('2024-05-03', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-05-03', 'Tesco', 'Groceries', 17.62, FALSE, 0.00, NULL),
  ('2024-05-06', 'Tesco', 'Groceries', 38.14, FALSE, 0.00, NULL),
  ('2024-05-08', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-05-08', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-05-09', 'Tesco', 'Groceries', 19.70, FALSE, 0.00, NULL),
  ('2024-05-10', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-05-10', 'Tesco', 'Groceries', 18.12, FALSE, 0.00, NULL),
  ('2024-05-12', 'Tesco', 'Groceries', 11.44, FALSE, 0.00, NULL),
  ('2024-05-13', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-05-13', 'MR Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2024-05-17', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-05-19', 'Tesco', 'Groceries', 38.01, FALSE, 0.00, NULL),
  ('2024-05-20', 'Tesco', 'Groceries', 10.47, FALSE, 0.00, NULL),
  ('2024-05-21', 'Tesco', 'Groceries', 1.75, FALSE, 0.00, NULL),
  ('2024-05-23', 'Tesco', 'Groceries', 6.00, FALSE, 0.00, NULL),
  ('2024-05-23', 'M and S', 'Groceries', 6.20, FALSE, 0.00, NULL),
  ('2024-05-24', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-05-25', 'T5 Stores', 'Groceries', 4.40, FALSE, 0.00, NULL),
  ('2024-05-28', 'MR Fizz', 'Gas', 23.60, TRUE, 3.92, NULL),
  ('2024-05-31', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-06-05', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-06-05', 'M and  S', 'Groceries', 1.75, FALSE, 0.00, NULL),
  ('2024-06-06', 'Tesco', 'Groceries', 9.13, FALSE, 0.00, NULL),
  ('2024-06-06', 'Amazon', 'jumbo playing cards', 21.99, TRUE, 3.67, NULL),
  ('2024-06-06', 'Amazon', 'Rainbow foil curtains', 12.99, TRUE, 2.17, NULL),
  ('2024-06-06', 'Amazon', 'bingo tickets', 3.99, TRUE, 0.67, NULL),
  ('2024-06-07', 'Simon Fridge man', 'fitting new parts', 150.00, FALSE, 0.00, NULL),
  ('2024-06-07', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-06-08', 'T5 Stores', 'Groceries', 1.89, FALSE, 0.00, NULL),
  ('2024-06-09', 'T5 Stores', 'Groceries', 10.38, FALSE, 0.00, NULL),
  ('2024-06-10', 'MF Fizz', 'Gas', 42.00, TRUE, 8.40, NULL),
  ('2024-06-10', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-06-12', 'Two Rivers', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-06-13', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-06-13', 'Tesco', 'Groceries', 15.79, FALSE, 0.00, NULL),
  ('2024-06-14', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-06-15', 'Tesco', 'Groceries', 8.25, FALSE, 0.00, NULL),
  ('2024-06-17', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-06-18', 'Tesco', 'Groceries', 28.33, FALSE, 0.00, NULL),
  ('2024-06-19', 'T5 Stores', 'Groceries', 2.69, FALSE, 0.00, NULL),
  ('2024-06-20', 'Poundland', 'prizes for high heels house party', 16.50, FALSE, 0.00, NULL),
  ('2024-06-21', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-06-21', 'T5 Stores', 'groceries', 2.50, FALSE, 0.00, NULL),
  ('2024-06-21', 'T5 Stores', 'Groceries', 1.85, FALSE, 0.00, NULL),
  ('2024-06-22', 'Tesco', 'Groceries', 20.03, FALSE, 0.00, NULL),
  ('2024-06-24', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-06-26', 'Nick Mclernon', 'high heels house party', 100.00, FALSE, 0.00, NULL),
  ('2024-06-26', 'Two Rivers', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-06-26', 'M and  S', 'Groceries', 3.20, FALSE, 0.00, NULL),
  ('2024-06-27', 'Tesco', 'Groceries', 3.30, FALSE, 0.00, NULL),
  ('2024-06-28', 'Tesco', 'Groceries', 9.90, FALSE, 0.00, NULL),
  ('2024-06-29', 'T5 Stores', 'Groceries', 4.29, FALSE, 0.00, NULL),
  ('2024-07-18', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-07-08', 'Westfield Carpark', 'Parking', 8.50, FALSE, 0.00, NULL),
  ('2024-07-17', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-07-01', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-07-05', 'M and S', 'Groceries', 3.10, FALSE, 0.00, NULL),
  ('2024-07-31', 'M and S', 'Groceries', 5.25, FALSE, 0.00, NULL),
  ('2024-07-22', 'M and S', 'Groceries', 2.00, FALSE, 0.00, NULL),
  ('2002-07-12', 'Tesco', 'Groceries', 4.32, FALSE, 0.00, NULL),
  ('2024-07-09', 'Tesco', 'Groceries', 5.15, FALSE, 0.00, NULL),
  ('2024-07-11', 'T5 Stores', 'Groceries', 3.18, FALSE, 0.00, NULL),
  ('2024-07-20', 'Tesco', 'Groceries', 67.26, FALSE, 0.00, NULL),
  ('2024-07-13', 'Tesco', 'Groceries', 8.22, FALSE, 0.00, NULL),
  ('2024-07-25', 'Tesco', 'Groceries', 5.05, FALSE, 0.00, NULL),
  ('2024-07-16', 'Tesco', 'Groceries', 6.44, FALSE, 0.00, NULL),
  ('2024-07-01', 'Tesco', 'Groceries', 68.04, FALSE, 0.00, NULL),
  ('2024-07-04', 'Tesco', 'Groceries', 3.70, FALSE, 0.00, NULL),
  ('2024-07-11', 'Tesco', 'Groceries', 29.50, FALSE, 0.00, NULL),
  ('2024-07-31', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-07-01', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-07-24', 'The Ardler Tavern', 'pub research menu layout food', 64.84, FALSE, 0.00, NULL),
  ('2024-07-10', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-07-14', 'Poundland', 'art for bits  quiz night', 4.00, FALSE, 0.00, NULL),
  ('2024-07-26', 'Poundland', 'gameshow prizes', 18.25, FALSE, 0.00, NULL),
  ('2024-07-08', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2024-07-06', 'TGI Fridays', 'team meal out', 218.75, FALSE, 0.00, NULL),
  ('2024-07-05', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-07-03', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-08-09', 'M and S (online)', 'Groceries', 20.00, FALSE, 0.00, NULL),
  ('2024-08-12', 'M and S', 'Groceries', 6.00, FALSE, 0.00, NULL),
  ('2024-08-19', 'M and S', 'Groceries', 10.00, FALSE, 0.00, NULL),
  ('2024-08-22', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-07', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-12', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-24', 'T5 Stores', 'Groceries', 3.58, FALSE, 0.00, NULL),
  ('2024-08-08', 'M and S', 'Groceries', 1.20, FALSE, 0.00, NULL),
  ('2024-08-06', 'Tesco', 'Groceries', 22.68, FALSE, 0.00, NULL),
  ('2024-09-20', 'Tesco', 'Groceries', 2.98, FALSE, 0.00, NULL),
  ('2024-08-31', 'Tesco', 'Groceries', 21.13, FALSE, 0.00, NULL),
  ('2024-08-27', 'Tesco', 'Groceries', 7.99, FALSE, 0.00, NULL),
  ('2024-08-19', 'Tesco', 'Groceries', 19.94, FALSE, 0.00, NULL),
  ('2024-08-17', 'Tesco', 'Groceries', 2.84, FALSE, 0.00, NULL),
  ('2024-08-02', 'Tesco', 'Groceries', 5.39, FALSE, 0.00, NULL),
  ('2024-08-13', 'Tesco', 'Groceries', 36.06, FALSE, 0.00, NULL),
  ('2024-08-03', 'Tesco', 'Groceries', 12.33, FALSE, 0.00, NULL),
  ('2024-08-09', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-16', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-19', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-14', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-08', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-08-05', 'Mr Fizz', 'Gas', 107.50, TRUE, 17.92, NULL),
  ('2024-08-21', 'T5 Stores', 'Groceries', 3.55, FALSE, 0.00, NULL),
  ('2024-09-25', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-05', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-09', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-06', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-17', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-09-14', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-03', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-19', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-09-11', 'The Works', 'Pens', 4.00, FALSE, 0.00, NULL),
  ('2024-09-13', 'Ryman', 'mouse', 16.99, FALSE, 0.00, NULL),
  ('2024-09-25', 'M and S', 'Groceries', 30.50, FALSE, 0.00, NULL),
  ('2024-09-04', 'M and S', 'Groceries', 4.55, FALSE, 0.00, NULL),
  ('2024-09-21', 'Tesco', 'Groceries', 5.38, FALSE, 0.00, NULL),
  ('2024-09-18', 'Tesco', 'Groceries', 9.88, FALSE, 0.00, NULL),
  ('2024-09-15', 'Tesco', 'Groceries', 3.79, FALSE, 0.00, NULL),
  ('2024-09-12', 'Tesco', 'Groceries', 7.50, FALSE, 0.00, NULL),
  ('2024-09-09', 'Tesco', 'Groceries', 2.95, FALSE, 0.00, NULL),
  ('2024-09-02', 'Tesco', 'Groceries', 8.29, FALSE, 0.00, NULL),
  ('2024-09-06', 'T5 Stores', 'Groceries', 3.80, FALSE, 0.00, NULL),
  ('2024-09-04', 'T5 Stores', 'Groceries', 1.90, FALSE, 0.00, NULL),
  ('2024-09-22', 'T5 Stores', 'Groceries', 3.00, FALSE, 0.00, NULL),
  ('2024-09-02', 'Mr Fizz', 'Gas', 63.00, TRUE, 10.50, NULL),
  ('2024-09-30', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2024-10-01', 'M and S', 'Groceries', 2.20, FALSE, 0.00, NULL),
  ('2024-10-01', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-01', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-03', 'M and S', 'Groceries', 3.10, FALSE, 0.00, NULL),
  ('2024-10-04', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-04', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-10-06', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-08', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-09', 'T5 stores', 'Groceries', 1.40, FALSE, 0.00, NULL),
  ('2024-10-09', 'Nish', 'Quiz Night', 30.00, FALSE, 0.00, NULL),
  ('2024-10-10', 'Tesco', 'Groceries/candles', 4.74, FALSE, 0.00, NULL),
  ('2024-10-10', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-14', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-15', 'Tesco', 'Groceries', 7.12, FALSE, 0.00, NULL),
  ('2024-10-16', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-17', 'Primark', 'Costume', 11.50, FALSE, 0.00, NULL),
  ('2024-10-18', 'Yasmin', 'Cleaning', 50.00, FALSE, 0.00, NULL),
  ('2024-10-19', 'M and S', 'Groceries', 1.45, FALSE, 0.00, NULL),
  ('2024-10-22', 'M and S', 'Groceries', 1.50, FALSE, 0.00, NULL),
  ('2024-10-22', 'M and S', 'Groceries', 2.10, FALSE, 0.00, NULL),
  ('2024-10-22', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-23', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-23', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-10-24', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-25', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-10-27', 'Amazon', 'make up', 4.59, TRUE, 0.77, NULL),
  ('2024-10-28', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2024-10-29', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-30', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-10-30', 'Nick Mclernon', 'high heels house party', 100.00, FALSE, 0.00, NULL),
  ('2024-10-31', 'Poundland', 'Groceries', 3.00, FALSE, 0.00, NULL),
  ('2024-10-31', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-01', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-11-02', 'Jemine Lake DJ', 'DJ', 300.00, FALSE, 0.00, NULL),
  ('2024-11-02', 'M and S', 'Groceries', 7.00, FALSE, 0.00, NULL),
  ('2024-11-02', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-02', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-03', 'Tesco', 'Groceries', 29.11, FALSE, 0.00, NULL),
  ('2024-11-04', 'Tesco', 'Groceries', 20.00, FALSE, 0.00, NULL),
  ('2024-11-05', 'M and S', 'Groceries', 2.95, FALSE, 0.00, NULL),
  ('2024-11-05', 'Wickes', 'PTFE Tape', 1.20, FALSE, 0.00, NULL),
  ('2024-11-05', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-05', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-06', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-07', 'Tesco', 'Groceries', 1.20, FALSE, 0.00, NULL),
  ('2024-11-08', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-08', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-11-09', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-11', 'Mr Fizz', 'Gas', 44.50, TRUE, 7.42, NULL),
  ('2024-11-12', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-13', 'Peter', 'Quiz night', 30.00, FALSE, 0.00, NULL),
  ('2024-11-14', 'Tesco', 'Groceries', 34.00, FALSE, 0.00, NULL),
  ('2024-11-15', 'Tesco', 'Groceries', 6.84, FALSE, 0.00, NULL),
  ('2024-11-15', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-15', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-11-18', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-18', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-11-21', 'Tesco', 'Groceries', 17.52, FALSE, 0.00, NULL),
  ('2024-11-22', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-11-22', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-11-23', 'Tesco', 'Groceries', 30.00, FALSE, 0.00, NULL),
  ('2024-11-25', 'Mr Fizz', 'Gas', 42.00, TRUE, 7.00, NULL),
  ('2024-11-26', 'Tk maxx', 'xmas dec', 20.98, FALSE, 0.00, NULL),
  ('2024-11-26', 'M and S', 'Groceries', 3.15, FALSE, 0.00, NULL),
  ('2024-11-27', 'Wickes', 'Fixers', 11.00, FALSE, 0.00, NULL),
  ('2024-11-27', 'Nick Mclernon', 'high heels house party game show', 100.00, FALSE, 0.00, NULL),
  ('2024-11-28', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-11-29', 'Tesco', 'Groceries', 17.46, FALSE, 0.00, NULL),
  ('2024-12-01', 'Dan', 'Fixing gate and f posts', 50.00, FALSE, 0.00, NULL),
  ('2024-12-01', 'Dan', 'Fixing gate and f posts', 120.00, FALSE, 0.00, NULL),
  ('2024-12-03', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-12-04', 'T5 Store', 'washing up liquid', 1.29, FALSE, 0.00, NULL),
  ('2024-12-05', 'Tesco', 'Groceries', 14.10, FALSE, 0.00, NULL),
  ('2024-12-06', 'Tesco', 'Groceries', 18.94, FALSE, 0.00, NULL),
  ('2024-12-06', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-12-11', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-12-11', 'peter', 'quiz night', 30.00, FALSE, 0.00, NULL),
  ('2024-12-12', 'Two Rivers Carpark', 'Parking', 2.30, FALSE, 0.00, NULL),
  ('2024-12-13', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-12-16', 'Ann Summers', 'Costume', 32.50, FALSE, 0.00, NULL),
  ('2024-12-17', 'Tesco', 'Groceries', 34.28, FALSE, 0.00, NULL),
  ('2024-12-18', 'Nick Mclernon', 'high heels house party game show', 100.00, FALSE, 0.00, NULL),
  ('2024-12-19', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-12-20', 'Tesco', 'Groceries', 6.15, FALSE, 0.00, NULL),
  ('2024-12-20', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-12-23', 'Tesco', 'Groceries', 6.60, FALSE, 0.00, NULL),
  ('2024-12-23', 'Tesco', 'Groceries', 11.85, FALSE, 0.00, NULL),
  ('2024-12-26', 'T5 Store', 'Groceries', 4.48, FALSE, 0.00, NULL),
  ('2024-12-26', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-12-28', 'Two Rivers Carpark', 'Parking', 1.30, FALSE, 0.00, NULL),
  ('2024-12-30', 'Tesco', 'Party Poppers', 3.50, FALSE, 0.00, NULL),
  ('2024-12-30', 'Poundland', 'Ballons Party poppers', 5.00, FALSE, 0.00, NULL),
  ('2024-12-30', 'Card Factory', 'Ballons Party poppers', 17.91, FALSE, 0.00, NULL),
  ('2024-12-30', 'Tesco', 'Groceries', 1.45, FALSE, 0.00, NULL),
  ('2024-12-31', 'Tesco', 'Groceries', 22.60, FALSE, 0.00, NULL),
  ('2024-12-31', 'Jemine Lake DJ', 'dj', 400.00, FALSE, 0.00, NULL),
  ('2024-07-05', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-07-12', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-07-19', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-08-02', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-08-19', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-08-16', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-08-23', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-08-30', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-08-14', 'Nish', 'Quiz Night', 30.00, FALSE, 0.00, NULL),
  ('2024-07-17', 'Nick Mclernon', 'game show paid by bank trans', 100.00, FALSE, 0.00, NULL),
  ('2024-08-25', 'Nick Mclernon', 'game show', 100.00, FALSE, 0.00, NULL),
  ('2024-09-06', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-09-13', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-09-20', 'Yasmin', 'Cleaning', 53.00, FALSE, 0.00, NULL),
  ('2024-09-27', 'Yasmin', 'Cleaning', 48.00, FALSE, 0.00, NULL),
  ('2024-09-30', 'Nick Mclernon', 'game show', 100.00, FALSE, 0.00, NULL);

