-- 1. Set immutable search_path on all functions (hardening, no behaviour change)
ALTER FUNCTION public.apply_balance_payment_status(p_booking_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.apply_customer_labels_retroactively() SET search_path = public, pg_catalog;
ALTER FUNCTION public.atomic_insert_parking_booking(p_customer_id uuid, p_customer_first_name text, p_customer_last_name text, p_customer_mobile text, p_customer_email text, p_vehicle_registration text, p_vehicle_make text, p_vehicle_model text, p_vehicle_colour text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_duration_minutes integer, p_calculated_price numeric, p_pricing_breakdown jsonb, p_override_price numeric, p_override_reason text, p_capacity_override boolean, p_capacity_override_reason text, p_status text, p_payment_status text, p_payment_due_at timestamp with time zone, p_expires_at timestamp with time zone, p_initial_request_sms_sent boolean, p_unpaid_week_before_sms_sent boolean, p_unpaid_day_before_sms_sent boolean, p_paid_start_three_day_sms_sent boolean, p_paid_end_three_day_sms_sent boolean, p_notes text, p_created_by uuid, p_updated_by uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.audit_booking_hold_status_change() SET search_path = public, pg_catalog;
ALTER FUNCTION public.auto_close_past_event_tasks() SET search_path = public, pg_catalog;
ALTER FUNCTION public.auto_generate_weekly_slots() SET search_path = public, pg_catalog;
ALTER FUNCTION public.booking_reminders_set_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_balance_due_date() SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_event_points(p_base_points integer, p_tier_id uuid, p_event_id uuid, p_member_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_message_cost(segments integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_next_generation_date(p_frequency character varying, p_frequency_interval integer, p_current_date date, p_day_of_month integer, p_day_of_week integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_private_booking_balance(p_booking_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_refund_amount(p_booking_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_refundable_balance(p_source_type text, p_source_id uuid, p_original_amount numeric) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_reminder_dates(event_date date, event_time text, has_seats boolean) SET search_path = public, pg_catalog;
ALTER FUNCTION public.calculate_send_time(p_event_timestamp timestamp with time zone, p_send_timing text, p_custom_hours integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.can_edit_invoice(invoice_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.categorize_historical_events() SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_and_reserve_capacity(p_service_date date, p_booking_time time without time zone, p_party_size integer, p_booking_type table_booking_type, p_duration_minutes integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_event_date_not_past() SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_expired_quotes() SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_overdue_invoices() SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_parking_capacity(p_start timestamp with time zone, p_end timestamp with time zone, p_ignore_booking uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_table_availability(p_date date, p_time time without time zone, p_party_size integer, p_duration_minutes integer, p_exclude_booking_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.check_tier_upgrade() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_expired_idempotency_keys() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_import() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_old_jobs() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_old_rate_limits() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_old_reminder_logs() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_old_service_slots() SET search_path = public, pg_catalog;
ALTER FUNCTION public.cleanup_old_webhook_logs() SET search_path = public, pg_catalog;
ALTER FUNCTION public.compare_employee_versions(p_employee_id uuid, p_version1 integer, p_version2 integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.count_receipt_statuses() SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_dish_transaction(p_dish_data jsonb, p_ingredients jsonb, p_recipes jsonb, p_assignments jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_employee_transaction(p_employee_data jsonb, p_financial_data jsonb, p_health_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_event_transaction(p_event_data jsonb, p_faqs jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_invoice_transaction(p_invoice_data jsonb, p_line_items jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_parking_booking_transaction(p_booking_data jsonb, p_payment_order_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_private_booking_transaction(p_booking_data jsonb, p_items jsonb, p_customer_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_quote_transaction(p_quote_data jsonb, p_line_items jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_recipe_transaction(p_recipe_data jsonb, p_ingredients jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_sunday_lunch_booking(p_customer_id uuid, p_booking_date date, p_booking_time time without time zone, p_party_size integer, p_special_requirements text, p_dietary_requirements text[], p_allergies text[], p_correlation_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.create_table_booking_transaction(p_booking_data jsonb, p_menu_items jsonb, p_payment_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.cron_job_runs_set_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.date_utc(timestamp with time zone) SET search_path = public, pg_catalog;
ALTER FUNCTION public.encrypt_sensitive_audit_data(p_encryption_key text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.enforce_parking_capacity() SET search_path = public, pg_catalog;
ALTER FUNCTION public.enforce_single_primary_vendor_contact() SET search_path = public, pg_catalog;
ALTER FUNCTION public.ensure_single_default_category() SET search_path = public, pg_catalog;
ALTER FUNCTION public.event_checklist_statuses_set_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_booking_reference() SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_invoice_reminder_digest() SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_loyalty_access_token() SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_parking_reference() SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_service_slots_for_period(start_date date, days_ahead integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_service_slots_from_config(start_date date, days_ahead integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_short_code(length integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_slots_from_business_hours(p_start_date date, p_days_ahead integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.generate_slots_simple() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_ai_usage_breakdown() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_all_users_with_roles() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_and_increment_invoice_series(p_series_code character varying) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_booking_discounted_total(p_booking_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_bookings_needing_reminders() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_category_regulars(p_category_id uuid, p_days_back integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_cross_category_suggestions(p_target_category_id uuid, p_source_category_id uuid, p_limit integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_customer_labels(p_customer_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_dashboard_stats() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_employee_at_timestamp(p_employee_id uuid, p_timestamp timestamp with time zone) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_employee_changes_summary(p_employee_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_invoice_summary_stats() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_message_template(p_event_id uuid, p_template_type text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_next_booking_reference() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_openai_usage_total() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_quarter_date_range(p_year integer, p_quarter integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_detail_groups(limit_groups integer, include_statuses text[], only_unclassified boolean, use_fuzzy_grouping boolean) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_detail_groups(limit_groups integer, include_statuses text[], only_unclassified boolean) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_monthly_category_breakdown(limit_months integer, top_categories integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_monthly_income_breakdown(limit_months integer, top_sources integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_monthly_status_counts(limit_months integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_monthly_summary(limit_months integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_receipt_vendor_trends(month_window integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_user_permissions(p_user_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_user_roles(p_user_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_vendor_invoice_email(p_vendor_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.handle_new_user() SET search_path = public, pg_catalog;
ALTER FUNCTION public.handle_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.import_receipt_batch_transaction(p_batch_data jsonb, p_transactions jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.increment_short_link_clicks(p_short_link_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.is_super_admin(check_user_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.log_audit_event(p_user_id uuid, p_user_email text, p_operation_type text, p_resource_type text, p_resource_id text, p_operation_status text, p_ip_address inet, p_user_agent text, p_old_values jsonb, p_new_values jsonb, p_error_message text, p_additional_info jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.log_invoice_audit(p_invoice_id uuid, p_action character varying, p_details jsonb, p_old_values jsonb, p_new_values jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.log_reminder_processing(p_processing_type text, p_message text, p_booking_id uuid, p_event_id uuid, p_customer_id uuid, p_template_type text, p_reminder_type text, p_error_details jsonb, p_metadata jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_get_latest_pack_cost(p_ingredient_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_get_latest_unit_cost(p_ingredient_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_refresh_dish_calculations(p_dish_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_refresh_recipe_calculations(p_recipe_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_trigger_refresh_after_dish_update() SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_trigger_refresh_after_price_change() SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_trigger_refresh_after_recipe_update() SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_trigger_refresh_dish_calculations() SET search_path = public, pg_catalog;
ALTER FUNCTION public.menu_trigger_refresh_recipe_calculations() SET search_path = public, pg_catalog;
ALTER FUNCTION public.mgd_collection_sync_return() SET search_path = public, pg_catalog;
ALTER FUNCTION public.normalize_and_enforce_booking_reminders() SET search_path = public, pg_catalog;
ALTER FUNCTION public.normalize_receipt_details(p_details text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.oj_mark_entries_paid_on_invoice_paid() SET search_path = public, pg_catalog;
ALTER FUNCTION public.performer_submissions_set_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.prevent_audit_log_deletion() SET search_path = public, pg_catalog;
ALTER FUNCTION public.prevent_audit_log_update() SET search_path = public, pg_catalog;
ALTER FUNCTION public.prevent_duplicate_reminders() SET search_path = public, pg_catalog;
ALTER FUNCTION public.prevent_event_delete_with_active_bookings() SET search_path = public, pg_catalog;
ALTER FUNCTION public.prevent_hard_delete_when_sms_sent() SET search_path = public, pg_catalog;
ALTER FUNCTION public.process_pending_jobs() SET search_path = public, pg_catalog;
ALTER FUNCTION public.queue_private_booking_sms(p_booking_id uuid, p_trigger_type text, p_template_key text, p_message_body text, p_recipient_phone text, p_customer_name text, p_priority integer, p_scheduled_for timestamp with time zone, p_metadata jsonb, p_skip_conditions jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.rebuild_customer_category_stats() SET search_path = public, pg_catalog;
ALTER FUNCTION public.record_balance_payment(p_booking_id uuid, p_amount numeric, p_method text, p_recorded_by uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.record_invoice_payment_transaction(p_payment_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.register_guest_transaction(p_event_id uuid, p_customer_data jsonb, p_staff_id uuid, p_labels jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.render_template(p_template text, p_variables jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.reserve_refund_balance(p_source_type text, p_source_id uuid, p_original_amount numeric, p_amount numeric, p_refund_method text, p_reason text, p_initiated_by uuid, p_paypal_capture_id text, p_paypal_request_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.restore_employee_version(p_employee_id uuid, p_version_number integer, p_user_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_booking_reference() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_cashup_target_override_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_loyalty_access_token() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_parking_booking_timestamps() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_parking_payment_timestamps() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_receipt_rules_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_receipt_transactions_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_receipt_vendor_watchlist_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_table_area_normalized_name_v05() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.short_link_is_known_bot(p_user_agent text, p_device_type text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.should_send_private_booking_sms(p_booking_id uuid, p_phone text, p_priority integer, p_trigger_type text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.standardize_phone_flexible(phone text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.sync_customer_name_from_customers() SET search_path = public, pg_catalog;
ALTER FUNCTION public.sync_event_start_datetime() SET search_path = public, pg_catalog;
ALTER FUNCTION public.trigger_log_invoice_changes() SET search_path = public, pg_catalog;
ALTER FUNCTION public.trigger_update_invoice_payment_status() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_customer_booking_stats() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_customer_category_stats() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_customer_messaging_health() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_customer_sms_status() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_dish_transaction(p_dish_id uuid, p_dish_data jsonb, p_ingredients jsonb, p_recipes jsonb, p_assignments jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_event_images_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_event_transaction(p_event_id uuid, p_event_data jsonb, p_faqs jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_invoice_payment_status(p_invoice_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_menu_target_gp_transaction(p_new_target_gp numeric, p_user_id uuid, p_user_email text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_messages_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_recipe_transaction(p_recipe_id uuid, p_recipe_data jsonb, p_ingredients jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.update_updated_at_column() SET search_path = public, pg_catalog;
ALTER FUNCTION public.user_has_permission(p_user_id uuid, p_module_name text, p_action text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.validate_booking_against_policy(p_booking_type table_booking_type, p_booking_date date, p_booking_time time without time zone, p_party_size integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.validate_employee_attachment_upload() SET search_path = public, pg_catalog;

ALTER VIEW public.cashup_weekly_view SET (security_invoker = true);
ALTER VIEW public.oj_project_stats SET (security_invoker = true);
ALTER VIEW public.menu_dishes_with_costs SET (security_invoker = true);
ALTER VIEW public.menu_ingredients_with_prices SET (security_invoker = true);

ALTER TABLE public.rota_google_calendar_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "rota_google_calendar_events_authenticated_all" ON public.rota_google_calendar_events FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.venue_space_table_areas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "venue_space_table_areas_authenticated_all" ON public.venue_space_table_areas FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.booking_table_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "booking_table_assignments_authenticated_all" ON public.booking_table_assignments FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.waitlist_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "waitlist_entries_authenticated_all" ON public.waitlist_entries FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.waitlist_offers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "waitlist_offers_authenticated_all" ON public.waitlist_offers FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.booking_holds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "booking_holds_authenticated_all" ON public.booking_holds FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "payments_authenticated_all" ON public.payments FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.charge_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "charge_requests_authenticated_all" ON public.charge_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "feedback_authenticated_all" ON public.feedback FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.guest_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "guest_tokens_authenticated_all" ON public.guest_tokens FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "analytics_events_authenticated_all" ON public.analytics_events FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.customer_scores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "customer_scores_authenticated_all" ON public.customer_scores FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.table_join_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY "table_join_links_authenticated_all" ON public.table_join_links FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.table_areas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "table_areas_authenticated_all" ON public.table_areas FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.event_interest_manual_recipients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "event_interest_manual_recipients_authenticated_all" ON public.event_interest_manual_recipients FOR ALL TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.sites ENABLE ROW LEVEL SECURITY;