-- Voucher system foundation (spec: tasks/voucher-system-spec-2026-07-30.md rev 3, sections 2, 7.2, 7.3).
-- Seven tables in F11 creation order, updated_at triggers, RLS enabled with no
-- policies (deny-all for anon and authenticated; all access is server-side via the
-- service-role client, which bypasses RLS), private storage bucket, seeds and RBAC.
--
-- Seed literals are generated by scripts/vouchers/extract-voucher-seed.ts from the
-- vendored handoff HTML (docs/design/voucher-system/), never retyped.
-- Ships dark: no UI, no cron; RPCs arrive in 20260802000002 as service-role only.

-- 1. voucher_types (controlled list, migration-seeded; spec 2.1)
create table public.voucher_types (
  id                text primary key,
  display_title     text not null,
  cover_title       text not null,
  value_pence       integer,
  requires_booking  boolean not null,
  alcohol           boolean not null,
  entitlement_html  text not null,
  hero              jsonb not null,
  copy              jsonb not null,
  sort_order        integer not null,
  active            boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- 2. terms_versions (spec 2.2; clauses is the ordered [{heading, body}] array)
create table public.terms_versions (
  version        text primary key,
  effective_from date not null,
  clauses        jsonb not null,
  published_by   text,
  created_at     timestamptz not null default now()
);

-- 3. voucher_batches (spec 2.4)
create table public.voucher_batches (
  id                uuid primary key default gen_random_uuid(),
  created_at        timestamptz not null default now(),
  created_by        uuid,                          -- auth user
  created_by_name   text not null,
  note              text,
  terms_version     text not null references public.terms_versions(version),
  type_definitions  jsonb not null,                -- F04 snapshot
  total_count       integer not null,
  pdf_status        text not null default 'pending'
                      check (pdf_status in ('pending','rendering','ready','failed')),
  pdf_path          text,                          -- immutable path incl. render version (F42)
  pdf_bytes         bigint,
  pdf_pages         integer,
  render_attempts   integer not null default 0,
  render_error      text,
  updated_at        timestamptz not null default now()
);

-- 4. voucher_number_counters (spec 2.7)
create table public.voucher_number_counters (
  month_key text primary key,                      -- '2607'
  last_seq  integer not null default 0
);

-- 5. vouchers (spec 2.4)
create table public.vouchers (
  id                  uuid primary key default gen_random_uuid(),
  voucher_number      text not null unique,        -- canonical uppercase 'AN-YYMM-NNNN'
  type_id             text not null references public.voucher_types(id),
  batch_id            uuid not null references public.voucher_batches(id),   -- RESTRICT (default)
  status              text not null check (status in
                        ('generated','issued','redeemed','expired','cancelled','replaced')),
  value_pence         integer,
  terms_version       text not null references public.terms_versions(version),
  -- hand-out
  issued_at           timestamptz,
  issued_by           uuid references public.employees(employee_id) on delete set null,
  issued_by_name      text,
  issued_by_user_id   uuid,                        -- authenticated account that performed it (F29)
  event_id            uuid references public.events(id) on delete set null,
  won_at_label        text,
  expiry_date         date,                        -- REQUIRED at issue (F02), London calendar date
  customer_id         uuid references public.customers(id) on delete set null,
  -- redemption
  redeemed_at         timestamptz,
  redeemed_by         uuid references public.employees(employee_id) on delete set null,
  redeemed_by_name    text,
  redeemed_by_user_id uuid,
  transaction_ref     text,
  booking_ref         text,
  -- lifecycle admin
  cancelled_at        timestamptz,
  cancelled_reason    text,
  replaced_by_id      uuid references public.vouchers(id) on delete set null,
  replaces_id         uuid references public.vouchers(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  -- lifecycle invariants (F15)
  constraint vouchers_issued_fields check (
    status not in ('issued','redeemed','expired')
    or (issued_at is not null and issued_by_name is not null
        and won_at_label is not null and expiry_date is not null)),
  constraint vouchers_redeemed_fields check (
    status <> 'redeemed' or (redeemed_at is not null and redeemed_by_name is not null)),
  constraint vouchers_cancelled_fields check (
    status not in ('cancelled','replaced') or (cancelled_at is not null and cancelled_reason is not null)),
  constraint vouchers_replaced_link check (
    status <> 'replaced' or replaced_by_id is not null),
  constraint vouchers_no_self_replace check (
    id <> replaced_by_id and id <> replaces_id)
);
create index idx_vouchers_status on public.vouchers (status);
create index idx_vouchers_type_status on public.vouchers (type_id, status);
create index idx_vouchers_batch on public.vouchers (batch_id);
create index idx_vouchers_event on public.vouchers (event_id) where event_id is not null;
create index idx_vouchers_customer on public.vouchers (customer_id) where customer_id is not null;
create index idx_vouchers_status_issued_at on public.vouchers (status, issued_at);
create index idx_vouchers_redeemed_at on public.vouchers (redeemed_at) where redeemed_at is not null;
create index idx_vouchers_expiry_issued on public.vouchers (expiry_date) where status = 'issued';
create unique index uq_vouchers_replaced_by on public.vouchers (replaced_by_id) where replaced_by_id is not null;  -- F14
create unique index uq_vouchers_replaces on public.vouchers (replaces_id) where replaces_id is not null;           -- F14

-- 6. voucher_events (authoritative audit trail; spec 2.4)
create table public.voucher_events (
  id                 uuid primary key default gen_random_uuid(),
  voucher_id         uuid not null references public.vouchers(id),
  action             text not null check (action in
                       ('generated','issued','redeemed','undo_redeem','expired','cancelled',
                        'replaced','reprinted','customer_assigned','customer_removed',
                        'reminder_sent','edited','override_redeemed','note')),
  actor_user_id      uuid,                          -- authenticated account (F43)
  actor_employee_id  uuid,                          -- selected staff member
  actor_name         text not null,                 -- snapshot
  source             text not null check (source in ('management','foh','cron','system')),
  at                 timestamptz not null default now(),
  detail             jsonb                          -- typed per action; customer_id only, never phone/name (F37)
);
create index idx_voucher_events_voucher_at on public.voucher_events (voucher_id, at desc);  -- F38

-- 7. voucher_reminders (F17 outbox)
create table public.voucher_reminders (
  id             uuid primary key default gen_random_uuid(),
  voucher_id     uuid not null references public.vouchers(id),
  customer_id    uuid references public.customers(id) on delete set null,
  reminder_kind  text not null check (reminder_kind in ('day30','day90','pre_expiry')),
  status         text not null default 'pending'
                   check (status in ('pending','sent','skipped','failed','cancelled')),
  scheduled_for  date not null,                     -- London date
  sent_at        timestamptz,
  message_sid    text,
  attempts       integer not null default 0,
  last_error     text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (voucher_id, reminder_kind)
);
create index idx_voucher_reminders_status_scheduled on public.voucher_reminders (status, scheduled_for);

-- updated_at maintenance (reuse existing convention: public.update_updated_at_column()).
create trigger voucher_types_set_updated_at
  before update on public.voucher_types
  for each row execute function public.update_updated_at_column();
create trigger voucher_batches_set_updated_at
  before update on public.voucher_batches
  for each row execute function public.update_updated_at_column();
create trigger vouchers_set_updated_at
  before update on public.vouchers
  for each row execute function public.update_updated_at_column();
create trigger voucher_reminders_set_updated_at
  before update on public.voucher_reminders
  for each row execute function public.update_updated_at_column();

-- RLS (F31): enabled with NO policies on all seven tables. anon and authenticated
-- are denied outright; the service-role client bypasses RLS, and every read/write
-- goes through server code after checkUserPermission. Deliberate deviation from the
-- checklists precedent, which added an explicit (redundant) service_role policy.
do $$
declare t text;
begin
  foreach t in array array[
    'voucher_types','terms_versions','voucher_batches','voucher_number_counters',
    'vouchers','voucher_events','voucher_reminders'
  ] loop
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;

-- Private storage bucket for batch PDFs (F42).
insert into storage.buckets (id, name, public)
values ('vouchers', 'vouchers', false)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Seeds. Generated verbatim from the handoff HTML by
-- scripts/vouchers/extract-voucher-seed.ts. Do not hand-edit these literals.
-- ---------------------------------------------------------------------------

INSERT INTO public.voucher_types
  (id, display_title, cover_title, value_pence, requires_booking, alcohol, entitlement_html, hero, copy, sort_order)
VALUES
  ($seed$free-drink$seed$, $seed$FREE DRINK VOUCHER$seed$, $seed$Free drink voucher$seed$, null, false, true, $seed$<p>This voucher may be exchanged for one of the following:</p><ul><li>One pint of any available draught product</li><li>One standard glass of house wine</li><li>One single standard spirit with a standard mixer</li><li>One regular soft drink</li></ul><p>Doubles, cocktails, premium spirits, bottles of wine, pitchers, sharers and packaged drinks are excluded unless expressly approved by a manager.</p>$seed$, $seed${"kind":"word","big":"One free","sub":"drink"}$seed$::jsonb, $seed${"headline":"Well, look at you","script":"Winning drinks and everything","prize":"A drink on us","open":"Your prize is inside","aside":"Pull up a chair. The first one&rsquo;s covered.","community":"There&rsquo;s always room for one more."}$seed$::jsonb, 1),
  ($seed$house-wine$seed$, $seed$BOTTLE OF HOUSE WINE$seed$, $seed$A bottle of house wine$seed$, null, false, true, $seed$<p>This voucher may be exchanged for one 750ml bottle of available house red, white or ros&eacute; still wine. It does not include sparkling wine, Champagne or premium bottled wine.</p><p>Alcohol may only be supplied to someone aged 18 or over, and valid photographic identification may be required.</p>$seed$, $seed${"kind":"word","big":"A bottle","sub":"of house wine"}$seed$::jsonb, $seed${"headline":"Wine not?","script":"You&rsquo;ve clearly earned it","prize":"A bottle of house wine","open":"Uncork this","aside":"Best enjoyed with good people and absolutely no rushing.","community":"Good bottles are better shared."}$seed$::jsonb, 2),
  ($seed$food-10$seed$, $seed$&pound;10 FOOD VOUCHER$seed$, $seed$&pound;10 food voucher$seed$, 1000, false, false, $seed$<p>This voucher provides &pound;10 towards food purchased from The Anchor&rsquo;s available food menu in one transaction. It cannot be used towards drinks.</p>$seed$, $seed${"kind":"money","big":"10","sub":"Food voucher"}$seed$::jsonb, $seed${"headline":"Something tasty has your name on it","script":"Go on, make a meal of it","prize":"&pound;10 towards food","open":"Tuck in","aside":"Good food, good people and no special occasion required.","community":"Good food brings people together."}$seed$::jsonb, 3),
  ($seed$drinks-10$seed$, $seed$&pound;10 DRINKS VOUCHER$seed$, $seed$&pound;10 drinks voucher$seed$, 1000, false, true, $seed$<p>This voucher provides &pound;10 towards drinks purchased from The Anchor&rsquo;s available drinks selection in one transaction. It cannot be used towards food.</p>$seed$, $seed${"kind":"money","big":"10","sub":"Drinks voucher"}$seed$::jsonb, $seed${"headline":"Your round just got better","script":"Cheers to that","prize":"&pound;10 towards drinks","open":"Drinks this way","aside":"Good drinks, better company and everyone welcome.","community":"Raise a glass to your local."}$seed$::jsonb, 4),
  ($seed$food-drink-25$seed$, $seed$&pound;25 FOOD &amp; DRINK VOUCHER$seed$, $seed$&pound;25 food &amp; drink voucher$seed$, 2500, false, true, $seed$<p>This voucher provides &pound;25 towards qualifying food and drinks purchased at The Anchor in one transaction.</p>$seed$, $seed${"kind":"money","big":"25","sub":"Food &amp; drink voucher"}$seed$::jsonb, $seed${"headline":"Now we&rsquo;re talking","script":"Dinner, drinks or a bit of both","prize":"&pound;25 to spend with us","open":"Decisions, decisions","aside":"Bring your appetite. Bringing your favourite people is strongly encouraged.","community":"Spend it on good times together."}$seed$::jsonb, 5),
  ($seed$roast-two$seed$, $seed$SUNDAY ROAST FOR TWO$seed$, $seed$Sunday roast for two$seed$, null, true, false, $seed$<p>This voucher may be exchanged for two standard Sunday roasts from the available Sunday menu.</p><p>It excludes starters, desserts, drinks, additional sides, upgrades and supplements. It is valid during advertised Sunday roast service and is not valid against special menus, private events or separately ticketed occasions unless expressly stated.</p><p>Availability is not guaranteed without an advance booking.</p>$seed$, $seed${"kind":"word","big":"Sunday roast","sub":"for two"}$seed$::jsonb, $seed${"headline":"Sunday plans: sorted","script":"You bring the company, we&rsquo;ll bring the gravy","prize":"Sunday roast for two","open":"Your Sunday starts here","aside":"Two plates. One table. Absolutely no washing up.","community":"Sundays are made for sharing."}$seed$::jsonb, 6),
  ($seed$quiz-four$seed$, $seed$FOUR QUIZ NIGHT TICKETS$seed$, $seed$Four quiz night tickets$seed$, null, true, false, $seed$<p>This voucher provides admission for up to four people to one standard public Quiz Night at The Anchor.</p><p>Advance booking is required and remains subject to event capacity. The voucher covers admission only and does not include food or drinks. The qualifying event must take place on or before the voucher&rsquo;s expiry date.</p>$seed$, $seed${"kind":"word","big":"Four tickets","sub":"Quiz night"}$seed$::jsonb, $seed${"headline":"Gather your smartest mates","script":"Or at least the loudest ones","prize":"Four quiz night tickets","open":"No Googling","aside":"Brains, banter and completely unjustified confidence.","community":"Every team needs a wildcard."}$seed$::jsonb, 7),
  ($seed$bingo-four$seed$, $seed$FOUR MUSIC BINGO TICKETS$seed$, $seed$Four music bingo tickets$seed$, null, true, false, $seed$<p>This voucher provides admission for up to four people to one standard public Music Bingo event at The Anchor.</p><p>Advance booking is required and remains subject to event capacity. The voucher covers admission only and does not include food or drinks. The qualifying event must take place on or before the voucher&rsquo;s expiry date.</p>$seed$, $seed${"kind":"word","big":"Four tickets","sub":"Music bingo"}$seed$::jsonb, $seed${"headline":"Your night just found a soundtrack","script":"Singing badly is strongly encouraged","prize":"Four music bingo tickets","open":"Turn it up","aside":"Four seats. Big tunes. Absolutely no dignity required.","community":"Every voice belongs in the chorus."}$seed$::jsonb, 8)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.terms_versions (version, effective_from, clauses, published_by)
VALUES ($seed$v2.0$seed$, DATE '2026-07-30', $seed$[{"heading":"Voucher entitlement","body":"This voucher may only be used for the entitlement printed on it. It does not provide any entitlement beyond the food, drink, monetary value or event entry specifically stated."},{"heading":"Validity","body":"This voucher is valid at The Anchor, Horton Road, Stanwell Moor Village, Surrey, TW19 6AQ, until close of business on the expiry date shown."},{"heading":"Expiry","body":"The voucher cannot normally be redeemed or extended after its expiry date. Where The Anchor cancels the qualifying event or is unable to provide the stated entitlement before the expiry date, a reasonable alternative or extension will be offered."},{"heading":"Unique voucher number","body":"Each voucher has a unique voucher number and may only be redeemed once. Its validity and redemption status will be checked against The Anchor&rsquo;s voucher system."},{"heading":"Presenting the voucher","body":"A valid printed or authorised digital voucher must be presented to a member of the team before ordering, paying or making the relevant booking."},{"heading":"Single redemption","body":"The voucher must be redeemed in full in one transaction or booking. It cannot be split across multiple transactions, visits or bookings."},{"heading":"Additional payment","body":"Where the total purchase exceeds the voucher&rsquo;s stated value or entitlement, the remaining amount must be paid using an accepted payment method."},{"heading":"Unused value","body":"No change, refund, credit or replacement voucher will be provided where the full monetary value or entitlement is not used."},{"heading":"No cash alternative","body":"The voucher cannot be exchanged for cash, refunded or used to obtain cashback."},{"heading":"Other vouchers and promotions","body":"Only one voucher may be used per transaction or booking. It cannot be combined with another voucher, discount, promotional offer or loyalty reward unless expressly stated."},{"heading":"Excluded purchases","body":"Unless the voucher specifically provides otherwise, it cannot be used towards event tickets, private-hire charges, deposits, gift vouchers, merchandise or any other non-food or non-drink purchase."},{"heading":"Availability and alternatives","body":"All food, drinks and events remain subject to availability. Where the exact item stated is unavailable, The Anchor may offer a reasonable alternative of an equal or greater value. No cash alternative will be provided."},{"heading":"Alcohol and age restrictions","body":"Alcohol may only be supplied to customers aged 18 or over. Valid photographic identification may be required. Customers under 18 may only use an eligible voucher towards non-alcoholic drinks or food."},{"heading":"Responsible service","body":"The supply of alcohol remains subject to licensing law and The Anchor&rsquo;s responsible service policies. The Anchor may refuse to supply alcohol where it would be unlawful or inappropriate to do so."},{"heading":"Event and booking vouchers","body":"Where advance booking is required, the voucher is not considered redeemed until the booking has been confirmed. Once applied to a confirmed booking, changes and cancellations are subject to the normal terms applying to that event."},{"heading":"Invalid vouchers","body":"A voucher will not be accepted where it is expired, altered, illegible, duplicated, already redeemed, replaced, cancelled in the voucher system or otherwise cannot be verified."},{"heading":"Lost or stolen vouchers","body":"Lost or stolen vouchers may only be replaced where the original voucher can be identified, has not been redeemed and can be cancelled in the voucher system. Replacement remains subject to verification."},{"heading":"Resale","body":"Promotional and prize vouchers must not be resold or offered for resale."},{"heading":"Queries and disputes","body":"Any query concerning the validity or redemption of a voucher will be reviewed by a manager against the voucher record, the stated entitlement and these terms."},{"heading":"Terms applying to the voucher","body":"The terms in force when the voucher is issued will apply to that voucher. They will not be changed retrospectively, except where required by law, and no change will reduce the stated entitlement of an already-issued voucher."},{"heading":"Statutory rights","body":"Nothing in these terms affects any statutory rights that cannot legally be excluded."}]$seed$::jsonb, $seed$Design handoff (docs/design/voucher-system)$seed$)
ON CONFLICT (version) DO NOTHING;

-- ---------------------------------------------------------------------------
-- RBAC: the vouchers module (F06, F30).
-- staff + foh_staff: view, edit (FOH surfaces). manager + super_admin: all four.
-- Deputy and portal_shift_manager receive nothing, mirroring the checklists
-- precedent (20260731000000), which granted them nothing either.
-- ---------------------------------------------------------------------------
insert into public.permissions (module_name, action, description) values
  ('vouchers', 'view',   'Look up vouchers and see FOH voucher counts'),
  ('vouchers', 'edit',   'Hand out, redeem and undo-redeem vouchers (FOH)'),
  ('vouchers', 'create', 'Generate voucher batches and print PDFs'),
  ('vouchers', 'manage', 'Full voucher management: ledger, detail, cancel, replace, overrides')
on conflict (module_name, action) do nothing;

-- staff + foh_staff: view, edit.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id from public.roles r cross join public.permissions p
where r.name in ('staff','foh_staff')
  and p.module_name = 'vouchers' and p.action in ('view','edit')
on conflict do nothing;

-- manager + super_admin: view, edit, create, manage.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id from public.roles r cross join public.permissions p
where r.name in ('manager','super_admin')
  and p.module_name = 'vouchers'
on conflict do nothing;
