import { describe, expect, it } from 'vitest'
import { buildOjInvoiceRevision, getOjInvoiceRevisionBlockReason } from '../invoice-revision'

describe('OJ Projects invoice revision', () => {
  it('blocks paid and partially paid invoices from revision', () => {
    expect(getOjInvoiceRevisionBlockReason({ status: 'paid' }, 0)).toBe(
      'Only unpaid active invoices can be revised from OJ Projects entries'
    )
    expect(getOjInvoiceRevisionBlockReason({ status: 'sent' }, 1)).toBe(
      'Cannot revise an invoice after a payment has been recorded'
    )
  })

  it('rebuilds detailed line items and totals from linked OJ rows', () => {
    const revision = buildOjInvoiceRevision({
      invoice: {
        invoice_number: 'INV-001',
        invoice_date: '2026-06-02',
        due_date: '2026-07-02',
        reference: 'OJ Projects 2026-06',
        notes: null,
        internal_notes: 'Auto-generated by OJ Projects billing run run-1 (2026-06).',
        invoice_discount_percentage: 0,
      },
      settings: {
        hourly_rate_ex_vat: 75,
        mileage_rate: 0.55,
        vat_rate: 20,
        statement_mode: false,
      },
      recurringInstances: [
        {
          id: 'rec-1',
          period_yyyymm: '2026-06',
          description_snapshot: 'Hosting',
          amount_ex_vat_snapshot: 50,
          vat_rate_snapshot: 20,
        },
        {
          id: 'rec-disabled',
          period_yyyymm: '2026-06',
          description_snapshot: 'Disabled hosting',
          amount_ex_vat_snapshot: 100,
          vat_rate_snapshot: 20,
          recurring_charge: { is_active: false },
        },
      ],
      entries: [
        {
          id: 'entry-time',
          entry_type: 'time',
          entry_date: '2026-06-02',
          project_id: 'project-1',
          project: { project_code: 'OJP-001', project_name: 'Retainer' },
          duration_minutes_rounded: 120,
          miles: null,
          hourly_rate_ex_vat_snapshot: 75,
          vat_rate_snapshot: 20,
          mileage_rate_snapshot: null,
          amount_ex_vat_snapshot: null,
          billable: true,
          description: 'Planning',
          work_type_name_snapshot: 'Admin',
        },
        {
          id: 'entry-mileage',
          entry_type: 'mileage',
          entry_date: '2026-06-03',
          project_id: 'project-1',
          project: { project_code: 'OJP-001', project_name: 'Retainer' },
          duration_minutes_rounded: null,
          miles: 10,
          hourly_rate_ex_vat_snapshot: null,
          vat_rate_snapshot: 0,
          mileage_rate_snapshot: 0.55,
          amount_ex_vat_snapshot: null,
          billable: true,
          description: 'Travel',
        },
      ],
      revisedAtIso: '2026-06-02T12:00:00.000Z',
    })

    expect(revision.lineItems).toEqual([
      expect.objectContaining({ description: 'Hosting', quantity: 1, unit_price: 50, vat_rate: 20 }),
      expect.objectContaining({ description: 'Mileage (10.00 miles @ GBP 0.550/mile)', quantity: 10, unit_price: 0.55, vat_rate: 0 }),
      expect.objectContaining({ description: 'OJP-001 - Retainer (2.00h)', quantity: 1, unit_price: 150, vat_rate: 20 }),
    ])
    expect(revision.lineItems).not.toEqual(
      expect.arrayContaining([expect.objectContaining({ description: 'Disabled hosting' })])
    )
    expect(revision.totals.subtotalBeforeInvoiceDiscount).toBe(205.5)
    expect(revision.totals.vatAmount).toBe(40)
    expect(revision.totals.totalAmount).toBe(245.5)
    expect(revision.notes).toContain('Invoice INV-001 revised 2026-06-02')
    expect(revision.internalNotes).toContain('OJ_PROJECTS_REVISED')
  })
})
